### ISSUE TITLE
error.security.client-token-invalid in create_session()

### ISSUE THREAD

**Issue by abialy** [ig-python/ig-markets-api-python-library#101]
It happens after an application is idle for some time. Doing logout() does not help. 

Any ideas? 

```
See some logs below:
create_session()
  File "/usr/lib/python3.6/site-packages/trading_ig/rest.py", line 1093, in create_session
    data = self.parse_response(response.text)
  File "/usr/lib/python3.6/site-packages/trading_ig/rest.py", line 236, in parse_response_with_exception
    raise(Exception(response['errorCode']))
Exception: error.security.client-token-invalid
```

**Comment by abialy** [comment]
Anyone has any idea how I can fix this?

**Comment by abialy** [comment]
Anyone? Is that project dead?

**Comment by oliverpolden** [comment]
Firstly, you can check if a project is alive by seeing if there are any recent commits. I've just checked the front page of this project and I can see a commit that was only two hours ago: https://github.com/ig-python/ig-markets-api-python-library
Secondly, this project is supported by people, like myself who are getting little or no payback but we get to all benefit from each other's generosity.
Comments such as "Is that project dead?" are pointless and serve no purpose except to annoy those that can potentially help you.

This is could be why you've had no response. (I also see that femtotrader edited your initial post for some reason, perhaps to make it more amenable).

Now, luckily for you I'm having this error as well so I'll see what I can do.
What I think I know at this point is that the token is fine but it expired so you need to get a new one. I make calls every minute in my system and it seems to sort itself out the next minute.

If anyone else has any info that could be helpful then that would be great. My investigation will be to see if I can find out an expiry time for the token and to automatically renew it. I will also look at handling the exception and again automatically renew. Again, I don't know this code so any pointers around where to catch the exception and how to renew it would be great.

**Comment by oliverpolden** [comment]
I've found this: https://labs.ig.com/rest-trading-api-reference/service-detail?id=523 which is the API reference for /session/refresh-token.
There doesn't seem to be an implementation of that (at least not in my local version and a quick search of the latest rest.py). So next I'm looking to handle that specific Exception by trying to refresh the token.
It's a bit difficult to test because I don't know when this happens. I'm assuming the token is valid for a specific amount of time. Although that call to /session/refresh-token says it responds with the expiry.

I'll create an implementation of /session/refresh, make a call to it and go on from there.

**Comment by oliverpolden** [comment]
Create session is using Version 2. And if I understand this page correctly, /session/refresh requires Version 3: https://labs.ig.com/node/557
Or does that mean that the request to /session/refresh needs to be Version 3?

**Comment by bug-or-feature** [comment]
I think the /session/refresh-token is only relevant if you have logged in with the v3 OAuth method, which is not yet implemented. The OAuth method has much faster token expiry. There is more info here: https://labs.ig.com/rest-trading-api-guide

**Comment by bug-or-feature** [comment]
FYI I don't know if it is relevant, but I think there were some issues with IG services the last few hours. The integration test failed at 1am UK time and was also failing at around 7am this morning. Seems to be resolved now

**Comment by bug-or-feature** [comment]
@oliverpolden are you still seeing the error?

**Comment by bug-or-feature** [comment]
Closing this issue. There's some new FAQs in the [docs](https://trading-ig.readthedocs.io/en/latest/faq.html) relating to login/sessions

**Comment by FlukeFan** [comment]
In case it helps anyone: for me, I found that I had to re-login (i.e., `POST` to `/session`) **60 seconds** after calling `/session` `PUT` to change the default account.

(This was a demo account - I don't know if the same timeout will be needed on a live account.)
