### ISSUE TITLE
Lightstreamer not getting market data

### ISSUE THREAD

**Issue by Viforel** [ig-python/ig-markets-api-python-library#102]
Hello,
First of all, thank you for the great work here!!!
I have a beginner's question on the data collection for the EURUSD live prices (and any currency pair in the end):
Once I am launching the lightstreamer.py, I am not getting any market data.

I am running the test and I can see my account in but there as well, no market data.

I tried this on both Demo and Live account.

My Subscription details in lightstreamer.py are:

>     subscription = Subscription(
>         mode="MERGE",
>         items=["CS.D.EURUSD.MINI.IP"],
>         fields=["stock_name", "last_price", "time", "bid", "ask"],
>         adapter="QUOTE_ADAPTER")

Thank you very much in advance,
V.

**Comment by Viforel** [comment]
I did a new, fresh install. I am a step further but still not in the right place seems so ... I am getting some information if I do not touch the items field but the info is kind of ... life beacon of the website I would say ..

> 
> Starting connection
> WARNING:__main__:systemd.daemon not available, no watchdog notifications will be sent.
> Ations Europe      : Last 14.06 - Time 17:24:05 - Bid 14.03 - Ask 14.06
> ELE Manufacturing  : Last  7.82 - Time 17:24:05 - Bid   7.8 - Ask  7.82
> Exacktum Systems   : Last 11.75 - Time 17:24:05 - Bid 11.72 - Ask 11.75
> Ations Europe      : Last 14.01 - Time 17:24:05 - Bid  14.0 - Ask 14.01
> Exacktum Systems   : Last 11.72 - Time 17:24:06 - Bid 11.72 - Ask 11.75
> Ations Europe      : Last 13.87 - Time 17:24:06 - Bid 13.84 - Ask 13.87
> KLA Systems Inc    : Last  3.51 - Time 17:24:06 - Bid  3.51 - Ask  3.52
> Bagies Consulting  : Last  7.75 - Time 17:24:07 - Bid  7.73 - Ask  7.75
> Ations Europe      : Last 13.71 - Time 17:24:07 - Bid 13.71 - Ask 13.73
> Ations Europe      : Last 13.83 - Time 17:24:07 - Bid 13.82 - Ask 13.83
> Exacktum Systems   : Last 11.81 - Time 17:24:07 - Bid 11.81 - Ask 11.84
> Ations Europe      : Last 13.93 - Time 17:24:07 - Bid 13.93 - Ask 13.96
> CVS Asia           : Last 16.86 - Time 17:24:07 - Bid 16.86 - Ask 16.92

Any hints please on how I could get the Forex Mini series?

Thank you

**Comment by sacharbit** [comment]
Hi @Viforel ,

A response a bit late but late is better than never right?

In the [documentation](https://labs.ig.com/streaming-api-reference) it tells you what to add in the field to make it work. Basically, "CS.D.EURUSD.MINI.IP" is not enough, you have to add at the beginning "MARKET:" if you want the "raw" prices, you can add "CHART:" with the period at the end (for example : "CHART:CS.D.EURUSD.MINI.IP:1MINUTE")

If you're still having the same problem, make sure that the items are good by checking on the [IG Stream Companion](https://labs.ig.com/streaming-api-reference).

If you're still having the problem and in ig stream companion, it works, then send the complete code you're executing.

**Comment by bug-or-feature** [comment]
Hi @Viforel did the suggestion help you? Closing otherwise...
