### ISSUE TITLE
minor typo in readme?

### ISSUE THREAD

**Issue by wangjian2020** [ig-python/ig-markets-api-python-library#104]
the readme file reads:
```
From source
Get latest version using Git
$ git clone https://github.com/ig-python/ig-markets-api-python-library
$ cd ig-markets-api-python-library
$ python setup.py install https://github.com/ig-python/ig-markets-api-python-library
or
$ pip install git+https://github.com/ig-python/ig-markets-api-python-library

```
the command `python setup.py install https://github.com/ig-python/ig-markets-api-python-library` should be `python setup.py install` right? because otherwise I get error `invalid command name 'https://github.com/ig-python/ig-markets-api-python-library'`

**Comment by femtotrader** [comment]
Thanks @wangjian2020 for reporting.
Fixed
