### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by lefig** [ig-python/ig-markets-api-python-library#105]
No issues, just a big thank you on behalf of all users.

This is a much needed project.

**Comment by femtotrader** [comment]
Nice issue.
You are welcome @lefig 
but a "big thank" could be, for me, getting a well paid job in finance / fintech industry.
An other good manner to send a big thank to open source contributors is by [contributing yourself](https://opensource.guide/how-to-contribute/).

**Comment by lefig** [comment]
Absolutely. I am learning python as quickly as my little brain permits. Giving back to the community is important.

**Comment by bug-or-feature** [comment]
Not an issue, closing
