### ISSUE TITLE
pandas.io.json deprecated

### ISSUE THREAD

**Issue by oliverpolden** [ig-python/ig-markets-api-python-library#107]
`from pandas.io.json import json_normalize`
Is raising a deprecation message and can now just be:
`from pandas import json_normalize`

https://github.com/ig-python/ig-markets-api-python-library/blob/719e356ecdc3619bdec2d8c057ef4df90e41e856/trading_ig/rest.py#L847

**Comment by femtotrader** [comment]
Thanks @oliverpolden 
It should be fixed in master now
