### ISSUE TITLE
Create Version 2 branch and deprecate version 1

### ISSUE THREAD

**Issue by oliverpolden** [ig-python/ig-markets-api-python-library#119]
I've just realised that the code is mostly based on version 1 on the API with specific calls to version 2. Some code that appears not to have been tested on version 2 is now broken. In the short term, this could be fixed by setting the broken code to use version 1 as has been done in other cases. However I don't think this is the right approach going forward.

I would like to create a Version 2 release branch, pin the API calls to use Version 2 and update the code accordingly. I don't think supporting both versions in the same branch is a good idea.

@femtotrader and anyone else with a vested interest. Are you happy for me to go this route? All it would mean at this stage is that we have a Version 2 branch that only works with Version 2 of the API.

Any other suggestions?

**Comment by Tarsopilami** [comment]
Hi, 

might this be the reason why 

calling
`ig_service.fetch_accounts()` 

produces following (excerpt) ?  

```
`~/anaconda3/lib/python3.7/site-packages/trading_ig-0.0.6-py3.7.egg/trading_ig/rest.py in read(self, endpoint, params, session, version)
    107         url = self._url(endpoint)
    108         session = self._get_session(session)
--> 109         self.HEADERS["LOGGED_IN"]["VERSION"] = version
    110         response = session.get(url, params=params, headers=self.HEADERS["LOGGED_IN"])
    111         return response

KeyError: 'LOGGED_IN'`
```

**Comment by oliverpolden** [comment]
Yes, “KeyError” errors are likely due to this version issue. You can either set the version to 1 (look at recent commits) or you can output/debug self.HEADERS to work out what it should be. 

Please post your findings and I’ll see if I can help sort it out.

**Comment by Tarsopilami** [comment]
Hello Oliver and thank you for your reply and offer to help.  

As a library for practice was badly needed, I chose the old ig_service.py from Lewis Barber on python 2.7 to work on in the meantime.  
Will try setting Version or sorting out self.HEADERS, when the newer library is needed.

**Comment by bug-or-feature** [comment]
Hi @oliverpolden. I don't think IG create new versions of their API endpoints in order that the older ones can be deprecated. I think they create a newer one, and keep the older one around in case anyone is till using it. Certainly the [Java library and sample app](https://github.com/IG-Group/ig-webapi-java-sample) supports all versions. I think we just need to be specific which one we're using, and it seems like recent changes have fixed those issues in this library.

**Comment by bug-or-feature** [comment]
PR #161 fixed the VERSION inconsistencies. Propose to close this unless anyone objects
