### ISSUE TITLE
Pandas object to_offset is unhashable

### ISSUE THREAD

**Issue by Weizhang2017** [ig-python/ig-markets-api-python-library#130]
https://github.com/ig-python/ig-markets-api-python-library/blob/b5799390752551f28038c258684259636ede8c8f/trading_ig/utils.py#L38

TypeError: unhashable type: 'pandas._libs.tslibs.offsets.Minute'

**Comment by RRMXkun** [comment]
Make sure you checkout the latest repo

`pip install git+https://github.com/ig-python/ig-markets-api-python-library`

**Comment by taradox** [comment]
> Make sure you checkout the latest repo
> 
> `pip install git+https://github.com/ig-python/ig-markets-api-python-library`

Hello,
I've installed the latest repo using the command you quoted, and I'm still getting the error that Weizhang2017 pointed out. Is there anything else we can do?
Thanks

**Comment by RRMXkun** [comment]
Ah yes, since v1.1 Pandas introduced a change which may be causing the problem. Can you please copy here the output of this command

`pip show pandas`

**Comment by taradox** [comment]
Yes I see, I do have Pandas 1.1.0. Here's the terminal output:

> Name: pandas
Version: 1.1.0
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: None
Author-email: None
License: BSD
Location: /home/arad/.local/lib/python3.8/site-packages
Requires: numpy, pytz, python-dateutil
Required-by: trading-ig

**Comment by RRMXkun** [comment]
Ok thanks, looks like the way freqs are used will need to change to accommodate the newer version. In the meantime @taradox @Weizhang2017 run this as a workaround:

`pip install 'pandas==1.0.5' --force-reinstall`
It'll get you up and running until a solution is implemented.

@femtotrader @oliverpolden this will be an issue for anyone who checks out the repo as pandas will automatically default to v1.1.0. Short term solution is to force a lower version to be used - PR coming shortly. However longer term the way frequencies are handled will need changing

**Comment by taradox** [comment]
Legend, thanks!

**Comment by RRMXkun** [comment]
You're welcome
Workaround in PR #132

**Comment by bug-or-feature** [comment]
PR #132 has been merged in, so closing
