### ISSUE TITLE
Add support for latest pandas

### ISSUE THREAD

**Issue by bug-or-feature** [ig-python/ig-markets-api-python-library#140]
Fix the underlying problem described by issue #130

**Comment by RRMXkun** [comment]
Actually looks like this may actually be a bug in Pandas rather than a feature, which they are potentially looking to fix: https://github.com/pandas-dev/pandas/pull/37288/commits

**Comment by bug-or-feature** [comment]
@RRMXkun well spotted, good news

**Comment by RRMXkun** [comment]
Pandas 1.1.4 release fixes the issue. Tested locally and working with latest version.

**Comment by Doggie52** [comment]
There's some new really useful plotting parameters introduced in pandas 1.1, `trading-ig` is the only thing holding my repo back from using the latest & greatest version!

**Comment by RRMXkun** [comment]
I have been using Pandas 1.1.4 since Nov with no issues. I'm happy to create a PR to remove the version requirement so it will default to the latest, as used to be the case. Would you object @bug-or-feature ?

**Comment by bug-or-feature** [comment]
@RRMXkun No objection. But maybe better to specify the new version in requirements.txt rather than remove it. Then it's clear to anyone new. And we won't be hurt the next time pandas releases a breaking change :)

**Comment by RRMXkun** [comment]
Addressed in PR #184 which you already merged, thanks @bug-or-feature. @Doggie52 you should be able to update from the repo and pandas 1.1.5 or 1.2.0 will install depending on which version of Python you're using.

**Comment by bug-or-feature** [comment]
Fixed by #184
