### ISSUE TITLE
Add a requirements.txt file with versions of the packages

### ISSUE THREAD

**Issue by Filco306** [ig-python/ig-markets-api-python-library#145]
As a reference to #130 and #140, these problems can occur if a `requirements.txt` is not added. I think a good addition would be to add it. This would add stability and safety to the package and would make it safer to use. 

I recently installed the latest release of the package (and only this package and nothing else) in a virtual environment, and my `requirements.txt` looks as below. 

```txt
certifi==2020.6.20
chardet==3.0.4
idna==2.10
infi.bunch==2.0.0
munch==2.5.0
numpy==1.19.2
pandas==1.0.5
pycryptodome==3.9.8
python-dateutil==2.8.1
python-dotenv==0.14.0
pytz==2020.1
requests==2.24.0
requests-cache==0.5.2
six==1.15.0
trading-ig==0.0.6
urllib3==1.25.10
```

Note that pandas 1.0.5 is installed, as it is the stable version for the package until the issue #140 is solved. 

Best,

**Comment by bug-or-feature** [comment]
I think we only need to include pandas, munch, pycryptodome, requests, requests-cache and six. The others are transitive. Create a PR if you like :)

**Comment by Filco306** [comment]
Cool, will do that when I have some time to spare :)

**Comment by Filco306** [comment]
See #146

**Comment by bug-or-feature** [comment]
Merged
