### ISSUE TITLE
Use pipenv for dependency management

### ISSUE THREAD

**Issue by bug-or-feature** [ig-python/ig-markets-api-python-library#149]

**Comment by bug-or-feature** [comment]
Even better - how about we use Poetry instead?

https://python-poetry.org/

Seems to combine the benefits of a virtual env with a robust packaging solution. 

Any thoughts? @oliverpolden @RRMXkun

**Comment by femtotrader** [comment]
Using a `pyproject.toml` file should probably be considered
https://www.python.org/dev/peps/pep-0631/
https://snarky.ca/what-the-heck-is-pyproject-toml/

**Comment by bug-or-feature** [comment]
Completed by release 0.0.10
