### ISSUE TITLE
fetch_historical methods should return a Panel of OHLCV historical data when symbols is a list of symbol

### ISSUE THREAD

**Issue by femtotrader** [ig-python/ig-markets-api-python-library#15]
`fetch_historical_prices_by_epic_and_num_points` or `fetch_historical_prices_by_epic_and_date_range` should also supports epic(symbol) as a list (instead of string) and it should returns a Panel of OHLCV historical data

**Comment by bug-or-feature** [comment]
Closing this, any solution would be in client code
