### ISSUE TITLE
conv_resol(resolution) gives an error: unhashable type

### ISSUE THREAD

**Issue by chopin-007** [ig-python/ig-markets-api-python-library#151]
I'm trying to apply resolution for fetch_historical_prices_by_epic_and_num_points and got stuck on conv_resol(resolution) which gives error of:

TypeError: unhashable type: 'pandas._libs.tslibs.offsets.Minute'

**Comment by bug-or-feature** [comment]
It sounds similar to #130. Make sure you're using the same pandas version as recommended in the requirements.txt file. A newer version will cause issues

**Comment by chopin-007** [comment]
> It sounds similar to #130. Make sure you're using the same pandas version as recommended in the requirements.txt file. A newer version will cause issues

`pip install 'pandas==1.0.5' --force-reinstall`

definitely helped. Although this issue will arise again for other users in the future... Would there be an update to the code to deal with newer panda versions?

Thank you!

**Comment by bug-or-feature** [comment]
See #140, contributions welcome
