### ISSUE TITLE
Implement v3 OAuth login method

### ISSUE THREAD

**Issue by bug-or-feature** [ig-python/ig-markets-api-python-library#157]
Will also need to implement /session/refresh-token

**Comment by bug-or-feature** [comment]
There is a need for this to be implemented now. If you are a user of IG L2 Dealer, you must have your ISA or Share Dealing account specified as the default account. However, that would mean starting up an API session would fail with v1 or v2 , with the dreaded `error.public-api.failure.stockbroking-not-supported` error. The v3 OAuth /session endpoint works however. Once logged in you have to switch to your spread bet or CFD account. I'll have a crack at it, may need some help testing

**Comment by kamiyechung** [comment]
@bug-or-feature Hello, thanks for all your great work. I am quite a beginner but would be happy to help you to test V3 OAuth login, if needed :)

**Comment by RRMXkun** [comment]
> There is a need for this to be implemented now. If you are a user of IG L2 Dealer, you must have your ISA or Share Dealing account specified as the default account. However, that would mean starting up an API session would fail with v1 or v2 , with the dreaded `error.public-api.failure.stockbroking-not-supported` error. The v3 OAuth /session endpoint works however. Once logged in you have to switch to your spread bet or CFD account. I'll have a crack at it, may need some help testing

I'll be happy to help testing also

**Comment by bug-or-feature** [comment]
Completed by release 0.0.10
