### ISSUE TITLE
Get all Epics

### ISSUE THREAD

**Issue by femtotrader** [ig-python/ig-markets-api-python-library#16]
A python method to get all epics will be nice

http://www.andlil.com/forum/epics-source-t9986.html#p308583
http://www.andlil.com/api/Epics/

from: https://github.com/ig-python/ig-markets-rest-api-python-library/issues/10

**Comment by 99epep** [comment]
I use this recursive design to get all epics from specific markets, should be easy to add one more level to pick up every epics.

`
import requests
import simplejson as json
import time

url = 'https://demo-api.ig.com/gateway/deal'
s = requests.Session()
s.headers = { 'Content-Type' : 'application/json; charset=UTF-8',
              'Accept' : 'application/json; charset=UTF-8',
              'VERSION' : '2',
              'X-IG-API-KEY' : 'Put Your API Key Here'
              }
data = { 'identifier' : 'YourID',
         'password' : 'yourPasswd'
         }
r = s.post(url + '/session', json=data)

s.headers.update({'X-SECURITY-TOKEN': r.headers['X-SECURITY-TOKEN'],
                  'CST': r.headers['CST'],
                  'VERSION' : '1'})

def exploreNode(nodeID, liste) :
    r = s.get(url + '/marketnavigation/' + nodeID)
    if isinstance( r.json()['nodes'], list ) :
        for node in r.json()['nodes'] :
            time.sleep(2)
            exploreNode(node['id'], liste)
    if isinstance( r.json()['markets'], list ) :
        for market in r.json()['markets'] :
            print(market['epic'])
            liste.append(market['epic'])

types = { 'FOREX_MINI':'264139',
          'INDICES_MINI':'264176',
          'MATIERES_PREMIERES_MINI':'264151',
          'FOREX':'195235',
          'INDICES':'97601',
          'MATIERES_PREMIERES':'101515',
          }

liste = []
for t in types.keys() :
    exploreNode( types[t], liste)
            
r = s.delete(url + '/session')

print(liste)
`

**Comment by femtotrader** [comment]
Thanks @99epep

**Comment by redbullpeter** [comment]
@femtotrader Are you planning to work on this? I've got some time I can spare on this.

**Comment by femtotrader** [comment]
I'm quite busy these days. So you can do it if you want but I think we should first cleanup code ( https://github.com/ig-python/ig-markets-api-python-library/issues/37 ), fix CI, add code coverage.

**Comment by redbullpeter** [comment]
OK will do some cleanup first.

**Comment by bug-or-feature** [comment]
There's a new sample script that shows how you could do this, see ``/samples/all_nodes.py``, however its not recommended. The full tree is massive, and it would take days to execute due to the rate limits.

There's a new FAQ about finding epics [here](https://trading-ig.readthedocs.io/en/latest/faq.html#how-do-i-find-the-epic-for-market-x)
