### ISSUE TITLE
rest.py - can't use fetch_accounts()

### ISSUE THREAD

**Issue by SLe-Corre** [ig-python/ig-markets-api-python-library#169]
fetch_accounts() fails with message:
"File "..\lib\site-packages\trading_ig\rest.py", line 279, in <lambda>
<lambda>
    data[colname] = ser.map(lambda x: x[col])
TypeError: 'NoneType' object is not subscriptable

Package is up to date (0.0.7)

Can retrieve trade information etc so connection to IG account is okay.

**Comment by bug-or-feature** [comment]
Hi @SLe-Corre there is an integration test that runs every night, and fetch_accounts() is one of the methods tested. It runs OK with no errors. Have a look under the Actions tab for the run history. 
Maybe check your dependencies match those in requirements.txt? If you're still having problems please attach a full stack trace

**Comment by SLe-Corre** [comment]
Hi @bug-or-feature, thanks for the quick response. Checked as you suggested, dependency versions are all up to date.
Did a bit more digging - call stack is suggesting it's erroring on an line of code that's been modified on the version thats on the readme.
It turns out the the version currently installed using `pipenv install trading_ig` returns an out of date version of the code, even though it's flagged at 0.0.7. Installing from git instead with `pipenv install git+https://github.com/ig-python/ig-markets-api-python-library#egg=NAME` creates a working copy.

Apologies for the relatively trivial issue.

**Comment by bug-or-feature** [comment]
@SLe-Corre no problem, I'm glad its resolved. I guess we should try to do releases to PyPI more often

**Comment by bug-or-feature** [comment]
0.0.8 released today
