### ISSUE TITLE
errors with REST

### ISSUE THREAD

**Issue by chopin-007** [ig-python/ig-markets-api-python-library#177]
File ".../lib/python3.8/site-packages/trading_ig/rest.py", line 295, in fetch_accounts
    data = self.parse_response(response.text)
  File ".../lib/python3.8/site-packages/trading_ig/rest.py", line 247, in parse_response_with_exception
    response = json.loads(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I keep getting this error at least once a day. I run my code for a few hours and then when there is a spike in volume very often I get kicked out and receive this error message. Anyone knows what I might change to improve the situation?

**Comment by chopin-007** [comment]
solved myself

**Comment by bug-or-feature** [comment]
Would you mind sharing your solution? It may help others with a similar problem

**Comment by chopin-007** [comment]
Sure, sorry I was about to do it the first time but I wanted to test my brilliant (you will see in a minute) solution:

The problem I had was that I made a mistake with quoting a dictionary element (historical prices)
_before:_
response = ig_service.fetch_historical_prices_by_epic_and_num_points(epic, resolution, num_points)
bid_prices = response**['prices']**['bid']

instead of using double quotation marks
_now:_
response = ig_service.fetch_historical_prices_by_epic_and_num_points(epic, resolution, num_points)
bid_prices = response**["prices"]**['bid']

I told you, it took a genius to solve it.
