### ISSUE TITLE
Exception: HTTP status code 403 {"errorCode":"error.public-api.failure.stockbroking-not-supported"} 

### ISSUE THREAD

**Issue by iEddie-cmd** [ig-python/ig-markets-api-python-library#178]
What does Exception: HTTP status code 403 {"errorCode":"error.public-api.failure.stockbroking-not-supported"}  mean?

**Comment by RRMXkun** [comment]
Which EPIC are you trading? Which account: spreadbetting, CFD, shares dealing?

**Comment by bug-or-feature** [comment]
I have seen this error. The resolution is to set your spread betting account to be the default. You can do this through the web platform or through the API

**Comment by iEddie-cmd** [comment]
Thank you. I would like to use my CFD Account for Trading and historical data. But i still get this error.

**Comment by bug-or-feature** [comment]
The solution I mentioned earlier worked for me, sorry if it does not for you. Maybe ask for help from the IG support team

**Comment by RRMXkun** [comment]
> 
> 
> Thank you. I would like to use my CFD Account for Trading and historical data. But i still get this error.

You may be using a stock dealing EPIC on a CFD account, or vice versa, hence my original question

**Comment by ChrisTram** [comment]
How can I set the CDF as default account through the API please ? On the French web version of IG there isn't the option to change it.

**Comment by ffent** [comment]
I'm facing the same issue while trying to stream price data from my CFD Demo account.
`Exception: HTTP status code 403 {"errorCode":"error.public-api.failure.stockbroking-not-supported"}`  

I have changed the EPIC to a CFD specific one (CS.D.CFEGOLD.CFE.IP) but still getting the same error message. Does anyone know a solution for this?

**Comment by RRMXkun** [comment]
As above, make sure you switch_account to your CFD account in case the default is the shares dealing account

**Comment by ffent** [comment]
Unfortunately this problem was solved after contacting the IG Labs Support. However, I'm not aware of the specific problem which caused this error.

**Comment by kamiyechung** [comment]
I just resolved the problem for me and maybe it could help someone.

It works when you set your default view on your IG account, but only if you connect on LIVE, not on DEMO mode (or if someone were able to do it, I would appreciate your help).
