### ISSUE TITLE
Why does this library require the use of IG login username and password? 

### ISSUE THREAD

**Issue by kimkevin2657** [ig-python/ig-markets-api-python-library#179]
I've taken look at the IG's API reference and none of them seem to require the user's login username and password in any of the headers. 

At most, they require the content type and the API key but that's about it.

**Comment by bug-or-feature** [comment]
[https://labs.ig.com/rest-trading-api-guide](https://labs.ig.com/rest-trading-api-guide)

look at the section on authentication and authorisation

**Comment by kimkevin2657** [comment]
> [https://labs.ig.com/rest-trading-api-guide](https://labs.ig.com/rest-trading-api-guide)
> 
> look at the section on authentication and authorisation

So i've looked at the authentication andnauthorisation part and it says

"""  
POST /session v1 and v2 return a CST header with a token identifying a client and an X-SECURITY-TOKEN header with a token identifying the current account. These headers should be passed on subsequent requests to the API. Both tokens are initially valid for 6 hours but get extended up to a maximum of 72 hours while they are in use.
"""

So those CST token and X-SECURITY-TOKEN token are access tokens not login username and password. 

Could you elaborate further about how the login username and password are necessary?
