### ISSUE TITLE
Metaprogramming

### ISSUE THREAD

**Issue by femtotrader** [ig-python/ig-markets-api-python-library#18]
Maybe metaprogramming could be a good idea
http://en.wikipedia.org/wiki/Metaprogramming

Example:

```
/prices/{epic}/{resolution}?startdate={startdate}&enddate={enddate} 
```

GET 1   Returns a list of historical prices for the given epic, resolution and date range.

`endpoint` is `/prices/{epic}/{resolution}`
`url_params` are `epic` and `resolution`. these parameters could be given using a dict.
`params` are `startdate` and `enddate`. these parameters are ever given using a dict.
`action` is `GET` (or `'read'`)
`help`is `Returns a list of historical prices for the given epic, resolution and date range.`
`version` is 1 (API version number)

After defining a structure for all API data (API v1 and v2) we should be able to reduce code.

Some input parameters (either `url_params` or `params`) need to be converted before API call.
Response also need to be converted (convert to DataFrame, or to dict...)

key of dict for `url_params` doesn't matter as it's an hidden variable but 
key of dict for `params` matters

from: https://github.com/ig-python/ig-markets-rest-api-python-library/issues/6

**Comment by xnox** [comment]
v3 api finally allows all types of queries back. Pull request sent.

**Comment by bug-or-feature** [comment]
I'm not sure what is being suggested here. Proposing to close unless anyone objects?
