### ISSUE TITLE
Why does this library require the use of login username and password?

### ISSUE THREAD

**Issue by kimkevin2657** [ig-python/ig-markets-api-python-library#180]
[https://labs.ig.com/rest-trading-api-guide](https://labs.ig.com/rest-trading-api-guide)
> 
> look at the section on authentication and authorisation

So i've looked at the authentication andnauthorisation part and it says

"""  
POST /session v1 and v2 return a CST header with a token identifying a client and an X-SECURITY-TOKEN header with a token identifying the current account. These headers should be passed on subsequent requests to the API. Both tokens are initially valid for 6 hours but get extended up to a maximum of 72 hours while they are in use.

POST /session v3 returns OAuth access and refresh tokens which the user can pass in subsequent API requests via the Authorization header, e.g.:
Authorization : Bearer 5d1ea445-568b-4748-ab47-af9b982bfb74
The access token only identifies the client so users should also pass an IG-ACCOUNT-ID header to specify the account the request applies to, e.g.:
IG-ACCOUNT-ID : PZVI2
The access token is only valid for a limited period of time (e.g. 60 seconds) specified by the login response.

"oauthToken": { "access_token": "702f6580-25c7-4c04-931d-6000efa824f8", "refresh_token": "a9cec2d7-fd01-4d16-a2dd-7427ef6a471d", "scope": "profile", "token_type": "Bearer", "expires_in": "60" }
"""

So those CST token and X-SECURITY-TOKEN token are access tokens not login username and password. 

Could you elaborate further about how the login username and password are necessary?

**Comment by RRMXkun** [comment]
Access tokens are generated with a call on /session. You will not have a token to refresh if you do not authenticate first. This is a very common method of handling authentication, not sure why you seem so surprised in the way it works.

**Comment by byod0** [comment]
@kimkevin2657, please close issue if is resolve.

**Comment by bug-or-feature** [comment]
No response, closing
