### ISSUE TITLE
I cannot open a position: 'reason': 'UNKNOWN', 'dealStatus': 'REJECTED'

### ISSUE THREAD

**Issue by Esteban108** [ig-python/ig-markets-api-python-library#186]
HI

I know this is not the right place to ask this, I'm sorry.
but I don't know what to do anymore, I wrote to IG several times before and the answers are bad.
I am trying to send an open operation to the API.

`ig_service.create_open_position(currency_code="SEK",`
                                                                `direction="BUY",`
                                                                `epic='CS.D.BITCOIN.CFD.IP', expiry="-", force_open=True,`
                                                                `guaranteed_stop=False, level=None, limit_distance=None,`
                                                                `limit_level=None, order_type="MARKET", quote_id=None,`
                                                                `size=str(0.3),`
                                                                `stop_distance=ig_market.dealingRules.minNormalStopOrLimitDistance.value, # 1.0`
                                                                `stop_level=None, trailing_stop=False,`
                                                                `trailing_stop_increment=None)`
But he always answers me
`...'reason': 'UNKNOWN', 'dealStatus': 'REJECTED'...`

Another example, the same result:
`ig_service.create_open_position(currency_code="SEK",`
                                                                `direction="BUY",`
                                                                `epic='CS.D.EURCHF.MINI.IP', expiry="-", force_open=True,`
                                                                `guaranteed_stop=False, level=None, limit_distance=None,`
                                                                `limit_level=None, order_type="MARKET", quote_id=None,`
                                                                `size=9,`
                                                                `stop_distance=44,`
                                                                `stop_level=None, trailing_stop=False,`
                                                                `trailing_stop_increment=None)`

Someone with more experience knows what I'm doing wrong?

I have tried with different markets, size

sometimes it works ... but most of it gives me this error.

what's going on?

Thanks!!!!

**Comment by RRMXkun** [comment]
Something that jumps out to me is
```
force_open=True,
guaranteed_stop=False
trailing_stop=False,
```
Try with 'false' and 'true' instead of False and True. These are not Python booleans, they are strings passed to the API.

**Comment by byod0** [comment]
@Esteban108 after your tests can you reply to continue or close issues.
There many issues open at this time.

**Comment by Esteban108** [comment]
Thanks! The result did not change, I keep getting the error. But there are some markets that work for me, for example Sweden30, and I send the same parameters to the api; maybe it's because I'm testing on a demo account?

**Comment by cfpavon** [comment]
This is what I have used and it works.

create_open_position(currency_code='USD',direction='BUY',epic='CS.D.BITCOIN.CFD.IP',

expiry='-',force_open='false',guaranteed_stop='false',order_type='MARKET',
size='1',
        level=None,
        limit_distance=None,
        limit_level=None,
        quote_id=None,
        stop_distance=None,
        stop_level=None,
        trailing_stop=None,
        trailing_stop_increment=None)

**Comment by Esteban108** [comment]
Thank you very much to all! I found the problem I thought that currency_code was the currency of my account, but it is the currency of the market.
