### ISSUE TITLE
Not receiving price stream data

### ISSUE THREAD

**Issue by alhennessey92** [ig-python/ig-markets-api-python-library#190]
I have used this library quite a lot last year, and after a break came back today to start using it again, however i have found that i am not able to stream any price data. 
i am using it with my spread betting demo account that i was using before.

I am able to connect, receive account data and establish a heartbeat subscription, but i am not receiving anything on my price subscription.
I am using the epic - MARKET:CS.D.EURUSD.TODAY.IP  of which i have tested on the IG labs streaming companion and i get data there.
Please find below the bulk of my connection code, its basically copied from your example template with the addition of the heartbeat subscription
Also, i am running this in a docker container in Kubernetes hosted on GKE google cloud platform, this is how i deployed it last year.

```
# A simple function acting as a Subscription listener
def on_prices_update(item_update):
    print("price: %s " % item_update, flush=True)
    print(
        "{stock_name:<19}: Time {UPDATE_TIME:<8} - "
        "Bid {BID:>5} - Ask {OFFER:>5}".format(
            stock_name=item_update["name"], **item_update["values"]
        ), flush=True
    )

def on_heartbeat_update(item_update):
    print(item_update["values"])

def on_account_update(balance_update):
    print("balance: %s " % balance_update, flush=True)


def main():
    logging.basicConfig(level=logging.INFO)
    # logging.basicConfig(level=logging.DEBUG)

    ig_service = IGService(
        config.username, config.password, config.api_key, config.acc_type
    )

    ig_stream_service = IGStreamService(ig_service)
    ig_session = ig_stream_service.create_session()
    # Ensure configured account is selected
    accounts = ig_session[u"accounts"]
    for account in accounts:
        if account[u"accountId"] == config.acc_number:
            accountId = account[u"accountId"]
            break
        else:
            print("Account not found: {0}".format(config.acc_number))
            accountId = None
    ig_stream_service.connect(accountId)

    # Making a new Subscription in MERGE mode
    subscription_prices = Subscription(
        mode="MERGE",
        items=["MARKET:CS.D.EURUSD.TODAY.IP"],
        fields=["UPDATE_TIME", "BID", "OFFER", "CHANGE", "MARKET_STATE"],
        adapter="QUOTE_ADAPTER"
    )
    # adapter="QUOTE_ADAPTER")

    # Adding the "on_price_update" function to Subscription
    subscription_prices.addlistener(on_prices_update)

    # Registering the Subscription
    sub_key_prices = ig_stream_service.ls_client.subscribe(subscription_prices)

    # Making an other Subscription in MERGE mode
    subscription_account = Subscription(
        mode="MERGE", items=["ACCOUNT:" + accountId], fields=["AVAILABLE_CASH"],
    )
    #    #adapter="QUOTE_ADAPTER")

    # Adding the "on_balance_update" function to Subscription
    subscription_account.addlistener(on_account_update)

    # Registering the Subscription
    sub_key_account = ig_stream_service.ls_client.subscribe(subscription_account)

    heartbeat_items = ["TRADE:HB.U.HEARTBEAT.IP"]
    heartbeat = Subscription(
        mode='MERGE',
        items=heartbeat_items,
        fields=["HEARTBEAT"],
    )

    heartbeat.addlistener(on_heartbeat_update)
    sub_heartbeat = ig_stream_service.ls_client.subscribe(heartbeat)

    input(
        "{0:-^80}\n".format(
            "HIT CR TO UNSUBSCRIBE AND DISCONNECT FROM \
    LIGHTSTREAMER"
        )
    )

    # Disconnecting
    ig_stream_service.disconnect()

    


if __name__ == "__main__":
    main()
```

**Comment by alhennessey92** [comment]
I have just tested this on a local kubernetes cluster and with a live account as well, i am still receiving account and heartbeat info but no price data.

**Comment by alhennessey92** [comment]
I have managed to get this working by removing the line 

`adapter="QUOTE_ADAPTER"`

What does the quote_adapter do? Why would it cause the price data to not be received

**Comment by RRMXkun** [comment]
> 
> 
> I have managed to get this working by removing the line
> 
> `adapter="QUOTE_ADAPTER"`
> 
> What does the quote_adapter do? Why would it cause the price data to not be received

Very good question. Looking at IG's example (in JavaScript) here: https://labs.ig.com/streaming-api-guide
They do not specify the adapter. From taking a look at Lightstreamer's documentation https://lightstreamer.com/docs/base/General%20Concepts.pdf (skip to page 7), the adapter is specified by IG, but I couldn't find QUOTE_ADAPTER anywhere. Suggest the sample file sample/stream_stock_list_demo.py is updated to that adapter is no longer referenced.

**Comment by Bravo27** [comment]
Each Lightstreamer client session is associated with a single Adapter Set, and each Adapter Set is made up of one Metadata Adapter and one or multiple Data Adapters.
So, if an Adapter Set has more than one Data Adapter the client subscription request must specify the name of the Data Adapter which will provide the data.

Probably in the case of IG the adapter Set has only one Data Adapter and no name has been specified in the configuration (DEFAULT is assumed). Therefore, during the subscription phase, the value for adapter must not be specified (or specify 'DEFAULT').
If you specify a Data Adapter name that is not present, the subscription request fails.

'QUOTE_ADAPTER' is the name of one of the Data Adapters of the Lighstreamer example online demos, in particular the StockList Demo. In that case the Adapter Set is DEMO and contains different Adapter Sets for the various Demos.
