### ISSUE TITLE
fetch_historical_prices_by_epic issue

### ISSUE THREAD

**Issue by jackyclever** [ig-python/ig-markets-api-python-library#192]
hi all, I am trying to use fetch_historical_prices_by_epic:

tickerPrice = ig_service.fetch_historical_prices_by_epic(epic1, start_date="2020-12-7", end_date="2020-12-8")

i have this error:

unauthorised.access.to.equity.exception

not sure why?

**Comment by RRMXkun** [comment]
You're referencing an epic that your account type does not have access to. Is it a crypto by any chance?

**Comment by jackyclever** [comment]
hi RRMXkun, it is Z1P, australia stock, epic is "AB.D.ZMLAU.CASH.IP"
my IG account is in AUD, I should be able to?

**Comment by RRMXkun** [comment]
@jackyclever remember to switch_account if you have more than one account type. Sometimes IG will pick the wrong account type by default.

**Comment by beekeweerts** [comment]
@RRMXkun I am a little confused that I cannot request data of an American stock with my standard CFD account (e.g. UC.D.NFLX.CASH.IP). Is this a normal behavior? Do you know if I can sign up any membership with IG to get this data as well?

**Comment by RRMXkun** [comment]
> 
> 
> @RRMXkun I am a little confused that I cannot request data of an American stock with my standard CFD account (e.g. UC.D.NFLX.CASH.IP). Is this a normal behavior? Do you know if I can sign up any membership with IG to get this data as well?

I have tried with my account: if I use my CFD account I get the same error. If I use my Spread Bet account I get the prices just fine. One for IG I'm afraid.
