### ISSUE TITLE
fetch_historical_prices_by_epic prices are divided by 100 for silver

### ISSUE THREAD

**Issue by Esteban108** [ig-python/ig-markets-api-python-library#194]
Hi, today i updated ig-trading to 0.0.9.

I am having a problem with fetch_historical_prices_by_epic.
He is giving me the price / 100. for the silver(CS.D.CFDSILVER.CFM.IP) with weekly prices, do not try others.
It only happened to me for this market. (Of which I saw)

Ig labs with version 3
![image](https://user-images.githubusercontent.com/33548508/112763688-df2fe580-8fdb-11eb-9d15-2d329132feaa.png)

trading-ig dataframe 
![image](https://user-images.githubusercontent.com/33548508/112763729-0c7c9380-8fdc-11eb-934a-b08fd45f7c71.png)

I tried debugging but didn't find anything wrong.

This did not happen with version 0.0.8.
until last week I have good prices.

thanks guys

**Comment by bug-or-feature** [comment]
The data frame in your second screenshot does not match the parameters given in the first, and you have not supplied the code you used to obtain the data frame shown in screenshot two.
How could anyone possibly determine what is wrong?

**Comment by Esteban108** [comment]
Sorry, This is a code for test it.
![image](https://user-images.githubusercontent.com/33548508/112827062-39748900-9064-11eb-83d2-3371efbc4087.png)



```
ig_service = IGService(user, pass, api_key, env)
ig_service.create_session()
prices = ig_service.fetch_historical_prices_by_epic('CS.D.CFDSILVER.CFM.IP', resolution="W",
                                                                     start_date='2021-2-27',
                                                                     end_date='2021-3-27'
                                                                     )
prices['prices'].head()

**Comment by bug-or-feature** [comment]
Sorry I cannot reproduce what you are seeing. Works OK in LIVE and DEMO

![Screenshot 2021-03-29 at 13 07 45](https://user-images.githubusercontent.com/8443008/112834859-69d21c80-9090-11eb-81cc-9b7f5444ddb9.png)

**Comment by Esteban108** [comment]
I do not understand anything, what is happening with my ig account ...
those prices come in the request data.
It is clear that the problem is IG
Thanks a lot.
