### ISSUE TITLE
"errorCode": null when fetch prices or get market

### ISSUE THREAD

**Issue by Esteban108** [ig-python/ig-markets-api-python-library#195]
Hi, me again

I am getting this error when I want to get the market or the prices or whatever.
It appears randomly, if I retry the call it works...
I think it comes from ig, from what I saw, but in the companion it does not happen to me.
the content of ig response is request_code = 500 content {"errorCode": null}

![image](https://user-images.githubusercontent.com/33548508/112832561-e0a8ee80-906b-11eb-81ec-a30d2f967dda.png)
```
ig_service = IGService(user, pass, api_key, env)
ig_service.create_session()
prices = ig_service.fetch_historical_prices_by_epic('CS.D.CFDSILVER.CFM.IP', resolution="W",
                                                                     start_date='2021-2-27',
                                                                     end_date='2021-3-29'
                                                                     )
market = ig_service.search_markets('EURUSD')
```
Thanks a lot!

**Comment by bug-or-feature** [comment]
If you think the problem is with IG, then this is not the place to report it. Try the IG community site, or IG support
