### ISSUE TITLE
Need help understanding

### ISSUE THREAD

**Issue by Clairvoyant88** [ig-python/ig-markets-api-python-library#196]
Hi Guys,

Thanks for the valuable contributions and codes. There are really very few helpful sources on lightstreamer in IG.

I hope someone can be kind enough to guide me on the codes. I am new to python, pandas, kivy, etc. I have coded my kivy GUI, REST for login, dealing, etc. But I am really very lost when it comes to lightstreamer. Hope someone can help with my queries.

I have look at:
https://github.com/ig-python/ig-markets-api-python-library/blob/master/trading_ig/lightstreamer.py
https://github.com/ig-python/ig-markets-api-python-library/blob/master/trading_ig/stream.py
https://github.com/ig-python/ig-markets-api-python-library/blob/master/sample/stream_ig.py

Would like to ask a few questions.

1) Why are there 3 different codes on steaming, what's the difference between the 3?

2) Do I import them as library or do I copy paste the codes in my GUI.

3) on lightstreamer.py, below indicates 12 items. does this mean that I can only have 12 subscriptions to IG where IG allowed us 40 concurrent subscriptions? Do I need to change this?
```
    # Making a new Subscription in MERGE mode
    subscription = Subscription(
        mode="MERGE",
        items=["item1", "item2", "item3", "item4", "item5", "item6", "item7", "item8", "item9", "item10", "item11", "item12",
        ],
        fields=["stock_name", "last_price", "time", "bid", "ask"],
        adapter="QUOTE_ADAPTER",
    )
```

4) Can I have multiple subscriptions from different items different fields in one line of code?

5) If can, does IG treat it as many subscriptions or treat it as one subcriptions?

6) Let's say if I am keen in the below data, how do I add it?
IX.D.NASDAQ.IFG.IP - OFFER, Latest 5 min candle OFR_HIGH, the previous latest 5 min candle OFR_HIGH (which is the second candle)
IX.D.SPTRD.IFG.IP - OFFER, Latest 5 min candle OFR_HIGH, the previous latest 5 min candle OFR_HIGH (which is the second candle)
Account Equity

I dont really understand lightstreamer fully, can all these different data item and field can be in one subscription? or I need to code multiple subscription.

Hope someone can help me with the questions.

Thank you.

Sincerely
Shaun

**Comment by dario-weswit** [comment]
1) The three codes shown are related to each other. The first one is a basic access library; the second one uses the first one to setup a connection; the third one uses the previous two to setup a connection and perform a subscription.

3) The subscription shown in the first code is just a sample subscription for Lightstreamer's demo installation and should be disregarded.

I have no answer for more specific questions. In general terms, Lightstreamer interface allows you to perform multiple subscriptions, with different choices of items and fields, within a single connection. You can collect multiple items in the same subscription provided that the requested fields are the same.

**Comment by Clairvoyant88** [comment]
Hi Dario,

Thanks for the guidance, I managed to figure it out. Seems like all the class and methods in ightstreamer.py are valid.

Just that to make it work in IG, need to change the way how we connect and subscribe. I roughly know how to connect. Just need to play around around with the subscription as I'm subscribing to quite a few items.

Thank you for the help! :)
