### ISSUE TITLE
Add dealReference to fetch_open_positions() - Closed position dealId no longer matches Open position dealId

### ISSUE THREAD

**Issue by oliverpolden** [ig-python/ig-markets-api-python-library#198]
This is probably mostly my own issue, but keen on feedback from anyone else:
I had a system working fine for a while but it seems IG now change the dealId shown on a closed position. This means that I can no longer match up closed positions with those in my database using the dealId.

IG also have a **dealReference** and the **/positions** endpoint returns it in the **position** object, but **fetch_open_positions()** does not include **dealReference** - https://github.com/ig-python/ig-markets-api-python-library/blob/master/trading_ig/rest.py#L538

I just checked the **create_working_order()** and that does seem to return **fetch_deal_by_deal_reference()** so I'm assuming that includes a deal reference that I can add to my orders and positions in my database so all should be good there.

I was probably using the API wrong myself as I believe the documentation says **dealReference** shouldn't change, unlike **dealId** which can.

I think all that needs to be done is to add **dealReference** to **fetch_open_positions()** but might be worth a quick check for any other places it might be missing.

I need to do some work on my own system to get **dealReference** into my database tables so will report any other findings and see if I can contribute my own changes.

**Comment by bug-or-feature** [comment]
@oliverpolden are you still seeing issues? The latest release has support for the ``/history/activity`` endpoints, which were not included at all previously. Can those functions help at all?

**Comment by bug-or-feature** [comment]
no response, closing
