### ISSUE TITLE
Add continuous integration with Travis CI

### ISSUE THREAD

**Issue by femtotrader** [ig-python/ig-markets-api-python-library#2]
we need tests for REST but also for STREAM API

**Comment by femtotrader** [comment]
it shoud help about Python 3 support https://github.com/femtotrader/ig-markets-stream-api-python-library/issues/5

**Comment by femtotrader** [comment]
there is some tests for REST API (sometimes failling because of API `error.public-api.exceeded-account-allowance` exception)

Maybe we should consider using mock

There is NO tests for STREAM API

Feel free to help

**Comment by bug-or-feature** [comment]
Closing this, CI build is fixed and stable
