### ISSUE TITLE
Lightstreamer error after days running on live

### ISSUE THREAD

**Issue by Esteban108** [ig-python/ig-markets-api-python-library#200]
Hi, 

My script was running for days, but it stopped on 04-24 at 00 with this error, I had two instances (in different markets) and both stopped at the same time, with the same error.

The error:
```
Exception in thread STREAM-CONN-THREAD-0:
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.8.7/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/.pyenv/versions/3.8.7/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.pyenv/versions/trading_algorithm_v1/lib/python3.8/site-packages/trading_ig/lightstreamer.py", line 380, in _receive
    self._forward_update_message(message)
  File "/home/ubuntu/.pyenv/versions/trading_algorithm_v1/lib/python3.8/site-packages/trading_ig/lightstreamer.py", line 324, in _forward_update_message
    table, item = int(tok[0]), tok[1]
ValueError: invalid literal for int() with base 10: ''

```

line of the error: [trading_ig/lightstreamer.py](https://github.com/ig-python/ig-markets-api-python-library/blob/master/trading_ig/lightstreamer.py#L324)

The error happens because tok [0] is '', I don't know what the implications of assuming a default of 1, I always use a single streamer.
Or, another solution could be to reconnect the Lightstreamer with another subscription once a day.
Do you recommend doing that?

Unfortunately I don't have the content of update_message to see that content.

Thank you so much!

**Comment by gfinocchiaro** [comment]
Hi,

actually, `tok[0]` references the subscription id (or the table number, same thing), therefore an empty string is something unexpected.
Without the full message, it is very hard figuring out what is going on.
Do you have any chance to raise the logging level to DEBUG?

**Comment by Esteban108** [comment]
l loss the logging output.  But the config was at INFO.
I close this issue because, I haven't had this problem anymore

**Comment by 108360232Zijie** [comment]
> l loss the logging output. But the config was at INFO. I close this issue because I haven't had this problem anymore

hey bro, I have the same problem, how do you fix it?
If you see my question plz reply to me thank.

**Comment by Esteban108** [comment]
> 
> 
> > l loss the logging output. But the config was at INFO. I close this issue because I haven't had this problem anymore
> 
> hey bro, I have the same problem, how do you fix it? If you see my question plz reply to me thank.

Hi, it just hasn't happened to me again. I don't change anything...

**Comment by marcipops** [comment]
Happened to me - nothing in my error log unfortunately.  Now raising logging from ERROR to DEBUG, as gfinocchiaro suggested and will report back if it traps anything.

Hope this is right - I'm using:
logging.basicConfig(filename='MH_Error.log', level=logging.DEBUG, format='%(asctime)s: %(funcName)s(): %(message)s')
