### ISSUE TITLE
Exception: HTTP status code 401 {"errorCode":"error.security.invalid-details"} 

### ISSUE THREAD

**Issue by ribboo** [ig-python/ig-markets-api-python-library#202]
Hello,
I'm unable to get my demo-account up and running. Getting stuck at wrong credentials, even though I've tried to switch them 10 times now. 

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    ig_service.create_session()
  File "/home/base/.local/lib/python3.8/site-packages/trading_ig/rest.py", line 1301, in create_session
    response = self._req(action, endpoint, params, session, version)
  File "/home/base/.local/lib/python3.8/site-packages/trading_ig/rest.py", line 230, in _req
    response = self.crud_session.req(action, endpoint, params, session, version)
  File "/home/base/.local/lib/python3.8/site-packages/trading_ig/rest.py", line 145, in req
    return d_actions[action](endpoint, params, session, version)
  File "/home/base/.local/lib/python3.8/site-packages/trading_ig/rest.py", line 90, in _create_first
    raise (
Exception: HTTP status code 401 {"errorCode":"error.security.invalid-details"} 
```

just using the sample code:
```
class config(object):
    username = "xxx"
    password = "xxx"
    api_key = "xxx"
    acc_type = "DEMO" # LIVE / DEMO
    acc_number = "xxx"
```
It works when I want to connect to my live account. But no the demo one. I have made separate credentials for the demo account within my account settings on IG. Feeling a bit lost here. Any ideas?

**Comment by singha24** [comment]
Hi did you ever manage to fix this?

**Comment by enghseb** [comment]
> Hi did you manage to fix this?

Yes, can't exactly remember what I did though. Think I just removed the account info line (line 7) using the code from the following page: https://trading-ig.readthedocs.io/en/latest/rest.html

**Comment by singha24** [comment]
Thanks! 

Im writing it from scratch and what helped me was changing the version from 2 to 3. So using OAuth instead of the other option and that worked for me

**Comment by RRMXkun** [comment]
@singha24 did you write login support for OAuth? That'd be a good addition to the current codebase

**Comment by bug-or-feature** [comment]
@RRMXkun I'm working on #157 - I'm testing currently on a dev branch. will be released soon

**Comment by madeinquant** [comment]
Encounter a same problem, login LIVE account successfully, but trading_ig triggered a exception "trading_ig.rest.IGException: HTTP error: 401 {"errorCode":"error.security.invalid-details"} " with DEMO account, I have already verify the username, password, api_key with ig demo account configuration so many times. However, it is still raise an exception, please feel free to comment. Thank you.

```
class config(object):
    username = "XXXX"
    password = "XXXX"
    api_key = "XXXXX"
    acc_type = "DEMO"  # LIVE / DEMO
    acc_number = "XXXXX"
```


```
from trading_ig import IGService
from trading_ig.config import config

ig_service = IGService(config.username, config.password, config.api_key,
                       config.acc_type.lower())
ig_service.create_session()

#account_info = ig_service.switch_account(config.acc_number,
#                                         False)  # not necessary
#print(account_info)

open_positions = ig_service.fetch_open_positions()
print("open_positions:\n%s" % open_positions)

print("")

epic = 'CS.D.EURUSD.MINI.IP'
resolution = 'S'
num_points = 10
response = ig_service.fetch_historical_prices_by_epic_and_num_points(
    epic, resolution, num_points)
df_ask = response['prices']['ask']
print("ask prices:\n%s" % df_ask)

```

**Comment by NewEconomicsUK** [comment]
Got the same problem using this

`from trading_ig import IGService
from trading_ig.config import config

ig_service = IGService(config.username, config.password, config.api_key, config.acc_type)
ig_service.create_session()

account_info = ig_service.switch_account(config.acc_number, False) # not necessary
print(account_info)

open_positions = ig_service.fetch_open_positions()
print("open_positions:\n%s" % open_positions)

print("")

epic = 'CS.D.EURUSD.MINI.IP'
resolution = 'D'
num_points = 10
response = ig_service.fetch_historical_prices_by_epic_and_num_points(epic, resolution, num_points)
df_ask = response['prices']['ask']
print("ask prices:\n%s" % df_ask)`

**Comment by mulucca** [comment]
why is it closed , what was the fix
