### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by oliverpolden** [ig-python/ig-markets-api-python-library#203]
As far as I can tell, this doesn't do any rate limiting so you'll get responses such as:
`Exception: HTTP status code 403 {"errorCode":"error.public-api.exceeded-api-key-allowance"}`

Info about rate limits here: https://labs.ig.com/faq#limits

We could use the ratelimit package do do this:
`from ratelimit import limits, sleep_and_retry`

And then decorate the appropriate function(s) such as the _req() function:
```    
@sleep_and_retry
@limits(calls=30, period=60)
def _req():
  ...
```

There are however two different rate limits: One for trading requests e.g. placing orders, opening positions. And another for non-trading requests such as getting historical data.
We could have two functions e.g. _req_trade() and _req_non_trade() and these simply both call _req() but can have their own decorators to use the appropriate limits. Or perhaps it might be easier for _req() to be given the rate limit decorator and assume it's for non-trade calls which makes up the bulk of the functions, and add a _req_trade() and update the trade functions to call that.

**Comment by bug-or-feature** [comment]
Hi Oliver
This is a more complex problem that it first appears. You can see that I attempted to make use of the `ratelimit`library in the [integration test](https://github.com/ig-python/ig-markets-api-python-library/blob/master/tests/test_integration.py). However, it did not work. After much frustration and digging, I found out that the DEMO environment has a completely different set of limits, and they're not fixed. IG support even told me that they frequently change the limits in DEMO to see how the platform reacts :)
I've started looking at another potential solution, which involves another library [tenacity](https://tenacity.readthedocs.io/en/latest/). This library takes a different approach, basically handling the error, and backing off longer and longer until it no longer fails. I'm using this on a dev branch for #157, and it solves the problem for the integration test. Implementing it in a way that works universally at the library level is harder though, (especially with the new v3 session stuff) and I'm still exploring it.

**Comment by oliverpolden** [comment]
Very interesting. Yes I have noticed that the rate limits don't behave predictably. So your approach with handling the error is probably better... assuming IG are ok with frequently making requests outside the limits. Your approach would also work if you have multiple threads and doesn't needlessly limit calls.

**Comment by bug-or-feature** [comment]
@oliverpolden new release 0.0.10 has some changes to make it a bit easier to use the tenacity library with this project. There is a new FAQ about it [here](https://trading-ig.readthedocs.io/en/latest/faq.html#how-to-avoid-hitting-the-rate-limits). Closing this

**Comment by grixxie** [comment]
Hi @bug-or-feature , very late to the party here but came across this page when Googling about the IG trading rate limits.
I'm being hit with the ```exceeded-api-key-allowance``` error in the demo spread betting environment. I'm writing an application that places a bunch of market orders at market open each day.

You mentioned above that the demo rate limits are different to the live limits - do you know why this is? Or how often they change? Does live typically have higher limits compared to demo?

Also, did you end up being able to solve this problem? Due to the nature of my application, I want to place many orders within a small amount of time, how would you recommend me solving this without simply waiting for the cooldown period to pass and trying again?
