### ISSUE TITLE
% python3 sample/stream_stock_list_demo.py

### ISSUE THREAD

**Issue by whittlem** [ig-python/ig-markets-api-python-library#205]
I'm trying out this library but it's not working for me.

	% python3 sample/stream_stock_list_demo.py 
	Starting connection
	WARNING:trading_ig.lightstreamer:systemd.daemon not available, no watchdog notifications will be sent.
	1
	----------HIT CR TO UNSUBSCRIBE AND DISCONNECT FROM     LIGHTSTREAMER-----------

I've been waiting ages and nothing had gone through. What is that warning and could it be preventing this from working on OSX?

I also tried this...

	% python3 sample/stream_ig.py                   
	can't import config from config file
	Account not found: <removed>
	INFO:trading_ig.stream:Starting connection with https://demo-apd.marketdatasystems.com
	WARNING:trading_ig.lightstreamer:systemd.daemon not available, no watchdog notifications will be sent.
	----------HIT CR TO UNSUBSCRIBE AND DISCONNECT FROM     LIGHTSTREAMER-----------
	balance: {'pos': 1, 'name': 'ACCOUNT:<removed>', 'values': {'AVAILABLE_CASH': '10000.00'}} 

Any ideas?

I waited over 5 minutes for each script and no output.

**Comment by whittlem** [comment]
I actually just noticed the "Account not found".

I'm assuming the problem may be here:
export IG_SERVICE_ACC_NUMBER=<removed>

I've tried the "clientId" and "accountId" from https://demo-api.ig.com/gateway/deal/session' and both say "Account not found". What needs to go into IG_SERVICE_ACC_NUMBER?

**Comment by whittlem** [comment]
I found a bug in the code. I'll raise a PR to fix it.

**Comment by whittlem** [comment]
I've fixed several sample script bugs in:
https://github.com/ig-python/ig-markets-api-python-library/pull/206

The script at least run for me now but still don't return any results?

	% python3 sample/stream_ig.py 
	INFO:trading_ig.stream:Starting connection with https://demo-apd.marketdatasystems.com
	WARNING:trading_ig.lightstreamer:systemd.daemon not available, no watchdog notifications will be sent.
	----------HIT CR TO UNSUBSCRIBE AND DISCONNECT FROM     LIGHTSTREAMER-----------
	balance: {'pos': 1, 'name': 'ACCOUNT:<removed>', 'values': {'AVAILABLE_CASH': '10000.00'}}

	% python3 sample/stream_stock_list_demo.py 
	Starting connection
	WARNING:trading_ig.lightstreamer:systemd.daemon not available, no watchdog notifications will be sent.
	1
	----------HIT CR TO UNSUBSCRIBE AND DISCONNECT FROM     LIGHTSTREAMER-----------

The two scripts just wait indefinitely but no pricing information ever comes through. What could be wrong?

% python3 --version
Python 3.9.5

I'm running OSX

**Comment by RRMXkun** [comment]
what does your subscription look like?

**Comment by whittlem** [comment]
I got it working but didn't use this library in the end. I just coded it myself.

**Comment by bug-or-feature** [comment]
@whittlem sorry you couldn't get the examples working. Hopefully the recent documentation changes will make things easier for new users. Closing
