### ISSUE TITLE
2 separate demo accounts

### ISSUE THREAD

**Issue by alexeyevgenov** [ig-python/ig-markets-api-python-library#207]
Hello.
I have an issue by using two demo accounts. It seems that the server does not work correctly through the "ig-trading" library. Request for 1st account has been sent to 2nd account and request for 2nd account has been sent to 1st account. Returns no positions. How can I control sessions at request time for each of the accounts?

**Comment by bug-or-feature** [comment]
There isn't enough info here. Have a look at the guidelines for asking questions [here](https://trading-ig.readthedocs.io/en/latest/faq.html#how-do-i-report-a-problem) and try again please

**Comment by bug-or-feature** [comment]
no response, closing
