### ISSUE TITLE
invalid.request.force_open

### ISSUE THREAD

**Issue by fjriosp** [ig-python/ig-markets-api-python-library#214]
When placing a working order with force_open=true I get this error:
`    o = self.ig.create_working_order(
  File "/mnt/nas/IGBot/venv/lib/python3.8/site-packages/trading_ig/rest.py", line 1023, in create_working_order
    raise IGException(response.text)
trading_ig.rest.IGException: {"errorCode":"invalid.request.force_open"}
`

**Comment by bug-or-feature** [comment]
https://trading-ig.readthedocs.io/en/latest/faq.html#what-if-i-have-a-problem

**Comment by bug-or-feature** [comment]
No response, closing
