### ISSUE TITLE
ig_service.fetch_historical_prices_by_epic Exception: Unable to parse datetime=2021-06-01 01:00:00

### ISSUE THREAD

**Issue by CZJ1018** [ig-python/ig-markets-api-python-library#217]
This is datetime's fomat but my code can’t  work.
:param start_date: (datetime, optional) date range start, format
            yyyy-MM-dd'T'HH:mm:ss
:param end_date: (datetime, optional) date range end, format
            yyyy-MM-dd'T'HH:mm:ss

**Comment by bug-or-feature** [comment]
There are some notes [here](https://trading-ig.readthedocs.io/en/latest/faq.html#what-if-i-have-a-problem) about seeking help with GitHub issues. Your issue may be closed and/or ignored if you do not follow the guidelines

**Comment by bug-or-feature** [comment]
No response, closing
