### ISSUE TITLE
Stream - create in stream.py objects to manage items, fields...

### ISSUE THREAD

**Issue by femtotrader** [ig-python/ig-markets-api-python-library#22]
Items:

```
MARKET, SPRINT_MARKET, ACCOUNT, TRADE, CHARTTICK, CHART
```

Mode:

```
MERGE, DISTINCT
```

https://labs.ig.com/sample-apps/streaming-companion/index.html
https://labs.ig.com/streaming-api-guide

Market price subscription (price availability subject to account permissions)

```
MARKET
    id: MARKET:{epic}
    mode: MERGE
    fields:
        BID
        OFFER
        HIGH
        LOW
        MID_OPEN
        CHANGE
        CHANGE_PCT
        MARKET_DELAY
        MARKET_STATE
        UPDATE_TIME
```

Sprint markets

```
SPRINT_MARKET
    id: MARKET:{epic}
    mode: MERGE
    fields:
        STRIKE_PRICE
        MARKET_STATE
        ODDS
```

Account subscription

```
ACCOUNT
    id: ACCOUNT:{accountid}
    mode: MERGE
    fields:
        PNL
        DEPOSIT
        AVAILABLE_CASH
        PNL_LR
        PNL_NLR
        FUNDS
        MARGIN
        MARGIN_LR
        MARGIN_NLR
        AVAILABLE_TO_DEAL
        EQUITY
        EQUITY_USED
```

An object oriented approach could be to create in stream.py (or somewhere else) objects to manage items, fields...

Trade subscription
    TRADE
        id: TRADE:{accountid}
        mode: DISTINCT
        fields:
            CONFIRMS
            OPU
            WOU

Chart subscriptions - Tick data

```
CHARTTICK
    id: CHART:{epic}:TICK
    mode: DISTINCT
    fields:
        BID
        OFR
        LTP
        LTV
        TTV
        UTM
        DAY_OPEN_MID
        DAY_NET_CHG_MID
        DAY_PERC_CHG_MID
        DAY_HIGH
        DAY_LOW
```

Chart subscriptions - Consolidated (candle) data

```
CHART
    id: CHART:{epic}:{scale} (ex: EPIC:SECOND|1MINUTE|5MINUTE|HOUR)
    mode: MERGE
    fields:
        {scale}
        LTV
        TTV
        UTM
        DAY_OPEN_MID
        DAY_NET_CHG_MID
        DAY_PERC_CHG_MID
        DAY_HIGH
        DAY_LOW
        DAY_PERC_CHG_MID
        DAY_HIGH
        DAY_LOW
        OFR_OPEN
        OFR_HIGH
        OFR_LOW
        OFR_CLOSE
        BID_OPEN
        BID_HIGH
        BID_LOW
        BID_CLOSE
        LTP_OPEN
        LTP_HIGH
        LTP_LOW
        LTP_CLOSE
        DAY_LOW
        CONS_END
        CONS_TICK_COUNT
```

Some epic examples: 'L1:CS.D.GBPUSD.CFD.IP', 'L1:CS.D.USDJPY.CFD.IP'

Maybe using Enum34 could help

**Comment by femtotrader** [comment]
See https://docs.python.org/3/library/enum.html

https://pypi.python.org/pypi/enum34

    Animal = Enum('Animal', ['ant', 'bee', 'cat', 'dog'], module=__name__)

**Comment by femtotrader** [comment]
An other approach could be to use traits / traitlets http://traitlets.readthedocs.org/en/latest/config.html

**Comment by bug-or-feature** [comment]
Is anyone still interested in this? I don't use the Stream part of the library, I cannot say if it would still be useful.

The issue has been untouched for 6 years; unless I hear otherwise I'll assume there's no need for it any more
