### ISSUE TITLE
Exception: error.security.account-token-invalid occurred when switch from default account to another account under the same IG username & password login

### ISSUE THREAD

**Issue by tospipdev** [ig-python/ig-markets-api-python-library#220]
Hi, I'm new to using this lib and so far it has really helped me to automate my trading.

I have two accounts (Spreadbet & CFD) opened under the same IG Username & Password login and ran into the below exception when trying to switch to the CFD account from my default account(Spreadbet).

After some research, it seems there is a bug from IG's REST APIs in which the security token string returned is doubled when there are multiple accounts - https://community.ig.com/forums/topic/15984-ig-api-switch-account/

Has anyone else ran into this issue and if so how can I resolve it in this lib?

![image](https://user-images.githubusercontent.com/48493474/130264297-7d20a95b-3537-4892-b091-28db38ce5174.png)

**Comment by tospipdev** [comment]
Resolved, added 'self._manage_headers(response)' to the switch account function in rest.py
![image](https://user-images.githubusercontent.com/48493474/130321428-69b0ab38-0be9-4db0-a470-b8a49d6a3d60.png)

**Comment by bug-or-feature** [comment]
@tospipdev thanks for spotting this. your code change has been added to the library.

please consider contributing with a PR next time
