### ISSUE TITLE
How can I close all positions at the same time？

### ISSUE THREAD

**Issue by CZJ1018** [ig-python/ig-markets-api-python-library#221]
Frist time i try:
My code:
      ig_service.close_open_position(deal_id = ig_service.fetch_open_positions()['dealId'].to_json(), direction='SELL',
                                epic=None, expiry=None, level=None, order_type="MARKET", quote_id=None,
                                size=1, session=None)
The system shows:
     trading_ig.rest.IGException: {"errorCode":"validation.pattern.invalid.request.dealId"}

Second time i try:
My code:
      ig_service.close_open_position(deal_id = ('DIAAAAGACAU4FAQ', 'DIAAAAGACDAE9AK'), direction='SELL',
                                epic=None, expiry=None, level=None, order_type="MARKET", quote_id=None,
                                size=1, session=None)
The system shows:
     trading_ig.rest.IGException: {"errorCode":"invalid.request.dealId"}

I don't want to use loop because the system limits 100 transaction requests per minute

**Comment by bug-or-feature** [comment]
@CZJ1018 there is no IG API method to close all positions - you would have to do it one at a time with your own code. See [this answer](https://trading-ig.readthedocs.io/en/latest/faq.html#how-to-avoid-hitting-the-rate-limits) in the FAQs about how to prevent API rate limit errors.
