### ISSUE TITLE
Guaranteed stoploss vanishes when working order is updated

### ISSUE THREAD

**Issue by Yianni-Mitropoulos** [ig-python/ig-markets-api-python-library#224]
Recently I noticed that updating a limit order / stop order using the `update_working_order` method results in the guaranteed stoploss being removed and replaced with an ordinary stoploss. Adding the keyword argument `guaranteed_stop=True` results in a runtime error.

**Comment by bug-or-feature** [comment]
@Yianni-Mitropoulos thanks for spotting this. It looks like the `guaranteedStop` option in `update_working_order()` has not been implemented. I'll fix this, may not be immediately

**Comment by Yianni-Mitropoulos** [comment]
You're welcome. Thanks for helping to maintain this code base, it's very generous of you.
