### ISSUE TITLE
Optional keyword arguments

### ISSUE THREAD

**Issue by Yianni-Mitropoulos** [ig-python/ig-markets-api-python-library#226]
I have a lot of code that looks like this:

`response = IG.create_open_position(
                    currency_code=CURRENCY,
                    direction=direction_str,
                    epic=self.ig_epic,
                    expiry=EXPIRY,
                    force_open=True,
                    guaranteed_stop=True,
                    level=None,
                    limit_distance=None,
                    limit_level=limit_level,
                    order_type="MARKET",
                    quote_id=None,
                    size=quantity_per_order,
                    stop_distance=stop_distance,
                    stop_level=None,
                    trailing_stop=False,
                    trailing_stop_increment=None
                )
`

It would be nice if more of the keyword arguments were optional (e.g. by giving them a default value of None or False). That way, the above code can look more like this:

`response = IG.create_open_position(
                    currency_code=CURRENCY,
                    direction=direction_str,
                    epic=self.ig_epic,
                    expiry=EXPIRY,
                    force_open=True,
                    guaranteed_stop=True,
                    limit_level=limit_level,
                    order_type="MARKET",
                    size=quantity_per_order,
                    stop_distance=stop_distance,
                )
`

In fact, I recommend going further: make _all_ the keyword arguments optional, and design a mechanism for setting up default values ahead of time.

For example, I envision that in one part of your program you might write something like:

`                IG.set_default_values(
                    currency_code=CURRENCY,
                    expiry=EXPIRY,
                    force_open=True,
                    guaranteed_stop=True,
                )
`

and then later, you could write

`                response = IG.create_open_position(
                    direction=direction_str,
                    epic=self.ig_epic,
                    limit_level=limit_level,
                    order_type="MARKET",
                    size=quantity_per_order,
                    stop_distance=stop_distance,
                )
`

thereby omitting all the "default" arguments.

**Comment by soltana80** [comment]
I am also new at python but python have a nice feature.

You can define default values in a dictionary and pass the dictionary as a parameter to the function.

Maybe this link will help you:
https://stackoverflow.com/questions/21986194/how-to-pass-dictionary-items-as-function-arguments-in-python/21986301

**Comment by bug-or-feature** [comment]
@Yianni-Mitropoulos thanks for the suggestion, but I'm not going to make any changes at this stage - sorry. The objective of this project is just to provide a simple low level wrapper for the IG API calls - each function maps directly to an API endpoint and the parameters match those provided by the API. The functionality you suggest may be more suitable for a higher level library, or perhaps some function in your own project
