### ISSUE TITLE
Avoid hitting the rate limits

### ISSUE THREAD

**Issue by CZJ1018** [ig-python/ig-markets-api-python-library#227]
Sorry, I don’t know what happens with this question, how can I fix it?
site-packages/trading_ig/rest.py", line 202, in _req
    result = self._retryer.call(self._request, action, endpoint, params, session, version, check)
AttributeError: 'Retrying' object has no attribute 'call'

**Comment by bug-or-feature** [comment]
@CZJ1018 you have not provided enough information. There are some notes [here](https://trading-ig.readthedocs.io/en/latest/faq.html#what-if-i-have-a-problem) about seeking help with GitHub issues. Your issue may be closed and/or ignored if you do not follow the guidelines

**Comment by CZJ1018** [comment]
My code:
from trading_ig.rest import IGService, ApiExceededException
from tenacity import Retrying, wait_exponential, retry_if_exception_type
from trading_ig.config import config
retryer = Retrying(wait=wait_exponential(), 
    retry=retry_if_exception_type(ApiExceededException))
ig_service = IGService(config.username, config.password, config.api_key, config.acc_type, acc_number=config.acc_number, retryer=retryer)

System report：
AttributeError: 'Retrying' object has no attribute 'call'

I don’t how to solve it,plz someone help me.

**Comment by bug-or-feature** [comment]
The guidelines [here](https://trading-ig.readthedocs.io/en/latest/faq.html#what-if-i-have-a-problem) list 5 items that must be included in an issue, you have provided none of them.

I'm sorry - I cannot help you without all the required information being included. Closing

**Comment by bug-or-feature** [comment]
hi @CZJ1018 I think I understand now what may have been causing your issue. Are you using tenacity version 8? 

If so, the ``call()`` method has been removed, hence your error. Two potential solutions: either use tenacity version 7, as specified in ``pyproject.toml``, or wait for the next release of this library which will support tenacity version 8.

If you had specified your dependency versions initially as suggested, I would have been able to identify your problem immediately
