### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by cfpavon** [ig-python/ig-markets-api-python-library#232]
I am using the stream api. Usually I have no problems with this but today it started acting up, i am not able to get chart prices. 

Any help will be appreciated. 

File "/home/cpavon/anaconda3/envs/trading_ig/lib/python3.8/http/client.py", line 915, in connect
    self.sock = self._create_connection(
  File "/home/cpavon/anaconda3/envs/trading_ig/lib/python3.8/socket.py", line 807, in create_connection
    raise err
  File "/home/cpavon/anaconda3/envs/trading_ig/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by BurningNacho** [comment]
I'm also having the same problem, everything was working smoothly until last friday!

**Comment by bug-or-feature** [comment]
Hi all, this is not the place to report or discuss issues like this. In future, please only report issues **with this library** here. You can see from the IG Community site that there were problems reported with Lightstreamer:

https://community.ig.com/forums/topic/16954-lightstreamer-connection-fail/

I have updated the [support FAQ](https://trading-ig.readthedocs.io/en/latest/faq.html#what-if-i-have-a-problem) in the docs with a checklist of actions to do before creating an issue here, please take a look. Issues created here may be closed and/or ignored without notice if these steps are not followed. Closing
