### ISSUE TITLE
Wrong/ Missing dependencies

### ISSUE THREAD

**Issue by hayunofek** [ig-python/ig-markets-api-python-library#239]
Hey, I found myself installing python libraries back and forth as trading_ig requires them as dependencies. I've stumbled upon these ones so far:

- pandas>1.0 (had a <1.0 version, and it didn't work, installing a newer >1.0 solved it) 
- munch
- tenacity

Where in the 'readthedocs' (https://trading-ig.readthedocs.io/en/latest/) site it only specifies 
-  requests
-  pycryptodome

as depenedencies.
Perhaps this should be added to the dependencies and specified somewhere?

**Comment by bug-or-feature** [comment]
As stated in the docs, the definitive source of information about dependencies is the [project config file](https://github.com/ig-python/ig-markets-api-python-library/blob/master/pyproject.toml). Everything there is to know about the dependencies is specified here. You should visit the [poetry docs](https://python-poetry.org/docs/) if anything is not clear.

Having said that, the docs for this project could be clearer. There is already a ticket to improve the docs around dependencies, see #216, so closing this one.
