### ISSUE TITLE
Open position Profit and Loss

### ISSUE THREAD

**Issue by alhennessey92** [ig-python/ig-markets-api-python-library#241]
Is there any way to retrieve the current profit and loss values of open positions?

I have looked through the REST API Reference on IG and can't find anything [IG REST API Ref](https://labs.ig.com/rest-trading-api-reference/service-detail?id=611)

Any help appreciated

**Comment by cfpavon** [comment]
As I understand, you can determiner retrieve your account PnL for all the open positions. However,  for each individual position, I calculated it by having the script store the "open price" and "position size", and requesting the "current price". The calculation also needs to take into account the spread, it is usually close enough depending on the volatility at the time.

**Comment by bug-or-feature** [comment]
The `fetch_transaction_history*()` functions show profit and loss. There are some example calls in the integration test
