### ISSUE TITLE
malformed date error

### ISSUE THREAD

**Issue by mehdimolum** [ig-python/ig-markets-api-python-library#244]
Hi, 
I am trying to get some historical data with rest api using the samples in the repo. 
I don't have problem when trying to get data using num_points:
```
num_points = 10
response = ig_service.fetch_historical_prices_by_epic_and_num_points( epic, resolution, num_points)
```
but when I try start_date/end_date, i.e., 
```
(start_date, end_date) = ('2021-09-15', '2021-09-28')
response = ig_service.fetch_historical_prices_by_epic_and_date_range(epic, resolution, start_date, end_date)
```
 I get `error.malformed.date`. I tried `(start_date, end_date) = ('15-09-2021', '28-09-2021')` but still the same error. wondering if there is something I am missing?

Thanks

**Comment by mehdimolum** [comment]
just in case someone else having the same issue, the start_date/end_date should be in the form of `yyyy-mm-dd hh:mm:ss`

**Comment by bug-or-feature** [comment]
@mehdimolum there are lots of examples of using this function in the unit and integration tests
