### ISSUE TITLE
Create a Limit order

### ISSUE THREAD

**Issue by univ1307** [ig-python/ig-markets-api-python-library#245]
Hi guys, i'm struggling to open a simple limit order. Can anyone kindly assist? 

 ig_service.create_open_position(
        currency_code='GBP',
        direction=d,
        epic = product,
        order_type='LIMIT',
        expiry='DFB',
        force_open='false',
        guaranteed_stop='false',
        size=abs(size), level=lvl,
        limit_distance=None,
        limit_level=None,
        quote_id=None,
        stop_level=None,
        stop_distance=None,
        trailing_stop=None,
        trailing_stop_increment=None)

#d = 'BUY', product = 'CS.D.USDJPY.TODAY.IP', lvl = 11475, size = 1

suspect i might be missing the time_in_force field from IG companion but don't know what's the correct name...

thanks a lot!!

**Comment by RRMXkun** [comment]
Can you post the full error message? are you opening a CFD or spread bet order?
