### ISSUE TITLE
fetch_historical_prices_by_epic_and_date_range error

### ISSUE THREAD

**Issue by jackyclever** [ig-python/ig-markets-api-python-library#247]
Hi all,

I am trying to use fetch_historical_prices_by_epic_and_date_range method to retrieve historical data, but it has error.malformed.date error.         

ig_service.fetch_historical_prices_by_epic_and_date_range(epic, resolution=resolution, start_date='2021-04-20', end_date='2022-03-14', version='2')

any idea? thank you in advance.

**Comment by bug-or-feature** [comment]
@jackyclever is your issue resolved?

**Comment by jackyclever** [comment]
Yes, it is resolved, thank you.

**Comment by bug-or-feature** [comment]
Thanks. For future reference, please close resolved issues
