### ISSUE TITLE
Creating a work order and setting Force Open to True generates a 400 error

### ISSUE THREAD

**Issue by SkiLtY** [ig-python/ig-markets-api-python-library#248]
In rest.py in create_working_order (v2 implementation) if you set force_open to True you receive a 400 error:

"errorCode":"invalid.request.force_open"

The issue is with the following code:

```
if force_open:
    params["force_open"] = 'true'
```

It should read:

```
if force_open:
    params["forceOpen"] = 'true'
```

**Comment by bug-or-feature** [comment]
@SkiLtY thanks, please consider submitting a fix

**Comment by SkiLtY** [comment]
@bug-or-feature have submitted the fix, bit new to submitting fixes but I think I got it right...

**Comment by bug-or-feature** [comment]
@SkiLtY there's one more step - you need to create a Pull Request. See the github docs

**Comment by bug-or-feature** [comment]
@SkiLtY all done - thanks for your contribution
