### ISSUE TITLE
Params error in REST create_open_position

### ISSUE THREAD

**Issue by cimourdain** [ig-python/ig-markets-api-python-library#25]
With the current code, when using the create_open_position function from REST API, i have the following error:
{"errorCode":"Failed to de-serialize entity [mediaType=application/json]"}

I solved the issue commenting the following lines in the positions params order:
```
        params = {
            'currencyCode': currency_code,
            'direction': direction,
            'epic': epic,
            'expiry': expiry,
            'forceOpen': force_open,
            'guaranteedStop': guaranteed_stop,
            'level': level,
            'limitDistance': limit_distance,
            'limitLevel': limit_level,
            'orderType': order_type,
            'quoteId': quote_id,
            'size': size,
            'stopDistance': stop_distance,
            'stopLevel': stop_level#,
            #'timeInForce': None,
            #'trailingStop': None,
            #'trailingStopIncrement': None
            
        }
```

**Comment by femtotrader** [comment]
Could you please send a pull request ?

**Comment by cimourdain** [comment]
sorry, i'm very new to github and i do not understand how to use pull requests. I tried to open one but i'm asked to compare versions and i'm a bit lost on this point ... i expected to find a place to just upload my updated version of the file.

**Comment by femtotrader** [comment]
Ok what is odd is that in current code

https://github.com/ig-python/ig-markets-api-python-library/blob/master/trading_ig/rest.py#L416

params dict looks like

```python
        params = {
            'currencyCode': currency_code,
            'direction': direction,
            'epic': epic,
            'expiry': expiry,
            'forceOpen': force_open,
            'guaranteedStop': guaranteed_stop,
            'level': level,
            'limitDistance': limit_distance,
            'limitLevel': limit_level,
            'orderType': order_type,
            'quoteId': quote_id,
            'size': size,
            'stopDistance': stop_distance,
            'stopLevel': stop_level
        }
```

Maybe you aren't using latest master version.

I suggest to `git clone` this repository (master branch) locally.

**Comment by cimourdain** [comment]
you are right, my bad.

**Comment by femtotrader** [comment]
Ok so I'm closing
Feel free to reopen in case of problem.
