### ISSUE TITLE
API Companion error with expiry field

### ISSUE THREAD

**Issue by squashdrinker** [ig-python/ig-markets-api-python-library#254]
I am using the IG API companion to familiarise myself with its use, with a view to creating an automated tool.
When I use 'Create working order' I get an error -
"errorCode": "validation.pattern.invalid.request.expiry"

I have tried many date patterns, and formats, none have worked so far.
Can you tell me what I should be entering in this field to satisfy the condition?

**Comment by bug-or-feature** [comment]
https://trading-ig.readthedocs.io/en/latest/faq.html#what-if-i-have-a-problem
