### ISSUE TITLE
Options Prices

### ISSUE THREAD

**Issue by JohnMcKenna1991** [ig-python/ig-markets-api-python-library#255]
Hi, 
Is there a way to get the options chain for gold or oil with this library?

**Comment by bug-or-feature** [comment]
I think someone who knows what an option chain is would be needed to answer this question. If the API can do it, then probably this library can help. I would check the docs for the API, or failing that, ask on the IG Community website. See [here](https://trading-ig.readthedocs.io/en/latest/faq.html#what-if-i-have-a-problem) for links

**Comment by JohnMcKenna1991** [comment]
OK thanks,
If I find a solution I will be sure to post it here. 

Regards,

John
