### ISSUE TITLE
good_till_date cannot be null in create_working_order

### ISSUE THREAD

**Issue by cimourdain** [ig-python/ig-markets-api-python-library#26]
Hi again,

In the REST api, in the `create_working_order` method, parameter `good_till_date` is converted to date. I noticed that this parameter is not mandatory and can be null. 

I would suggest to replace in the trading_ig/rest.py file on line 518

`good_till_date = conv_datetime(good_till_date, 1)`

by 
```python
if good_till_date != None:
            good_till_date = conv_datetime(good_till_date, 1)
```

**Comment by femtotrader** [comment]
Ok I did

```python
    def create_working_order(self, currency_code, direction, epic, expiry,
                             guaranteed_stop, level,
                             limit_distance, limit_level, size, stop_distance,
                             stop_level, time_in_force, order_type,
                             good_till_date=None,
                             session=None):
        """Creates an OTC working order"""

        if good_till_date is not None:
            good_till_date = conv_datetime(good_till_date, 1)
```

see https://github.com/ig-python/ig-markets-api-python-library/commit/372e7fcdf8fda8319f351feb08fd615615e02182

You just need to git checkout

Feel free to reopen this issue if it's not correctly solved
