### ISSUE TITLE
opening a position or a work  order

### ISSUE THREAD

**Issue by ZonyLaw** [ig-python/ig-markets-api-python-library#262]
I have been testing the open position code which works as outlined in the 'https://trading-ig.readthedocs.io/en/latest/quickstart.html#using-the-rest-api'.
However, how to put stops and limits in the parameter. I thought it just take in some number but error is returned as below.

For example, I try something like a sell limit with some limit level
I don't think it is responding as it should as it doesn't like any numbers entered for these parameters. Also it doesn't accept STOP as argument for 'order_type'. Any advice on this would be greatly appreciated. In fact, I am interested in doing a working order. Does the package allow us to do this?

-----------------------code used
resp = ig_service.create_open_position(
currency_code='GBP',
direction='SELL',
epic='CS.D.USDJPY.TODAY.IP',
order_type='LIMIT',
expiry='DFB',
force_open='false',
guaranteed_stop='false',
size=1.0,
level=None,
limit_distance=None,
limit_level=None,
quote_id=None,
stop_level=15000,
stop_distance=None,
trailing_stop=None,
trailing_stop_increment=None)

print(resp)
---------------------output

Traceback (most recent call last):
File "C:\Users\sunny\Desktop\Development\python\py_igTrading2\ig-markets-api-python-library\sample\test.py", line 155, in
main()
File "C:\Users\sunny\Desktop\Development\python\py_igTrading2\ig-markets-api-python-library\sample\test.py", line 106, in main
resp = ig_service.create_open_position(
File "C:\Users\sunny\Desktop\Development\python\py_igTrading2\ig-markets-api-python-library\trading_ig\rest.py", line 988, in create_open_position
raise IGException(response.text)
trading_ig.rest.IGException: {"errorCode":"validation.target-value-conditional-set-value.request"}

**Comment by galburn** [comment]
Try sending the numeric values as text strings in quotes.

**Comment by ZonyLaw** [comment]
I try that but it doesn't work. Does anyone have a working example with stops or limits entered?

**Comment by galburn** [comment]
This is for creating working orders which are similar:-

![image](https://user-images.githubusercontent.com/8711267/189225517-ad9691d2-cb9f-474a-b3f0-7580120e0b83.png)

**Comment by galburn** [comment]
This might also help:-
https://community.ig.com/forums/topic/12676-invalidheader-error-for-creating-working-order-through-trading_ig-api/

**Comment by ZonyLaw** [comment]
Thanks, your advice and the link is very helpful. Exactly what I am looking for.
