### ISSUE TITLE
timeInForce and dealReference missing on create_open_position

### ISSUE THREAD

**Issue by firebird631** [ig-python/ig-markets-api-python-library#264]
on method create_open_position two parameters are missing :

timeInForce that could be EXECUTE_AND_ELIMINATE or FILL_OR_KILL
dealReference optional string

The trailingStop might be false by default and trailingStopIncrement none.

**Comment by bug-or-feature** [comment]
If you think there is a bug, please create a PR

**Comment by firebird631** [comment]
It is not a bug it is a possible lack of 2 useful parameters (at least dealReference for retrieving position).
Sorry but I will not do a PR for 2 lines of code.
I let the pro do it.
Regards.
