### ISSUE TITLE
Stream API - Do not receive anything for account, confirms, OPU etc.

### ISSUE THREAD

**Issue by cimourdain** [ig-python/ig-markets-api-python-library#27]
Hi again,

I tried to use the stream API based on the stream_ig.py file in the sample folder. Price update part works perfectly, on the other hand the account update part does not. In debug mode, i only get PROBE from lightstreamer (i tried to update account by closing positions and making a deposit and still nothing received). The following message repeat indefinitely

```
DEBUG:trading_ig.lightstreamer:Waiting for a new message
DEBUG:trading_ig.lightstreamer:Received message ---> <PROBE>
DEBUG:trading_ig.lightstreamer:PROBE message
```

In the same way, i cannot get the TRADE part working, i do not get any reception whith the following parameters:

```
        subscription_trades = Subscription(
            mode="DISTINCT",
            items='TRADE:'+self.accountId,
            fields=["CONFIRMS","OPU", "WOU"],
            )
```

thanks for your help,

**Comment by femtotrader** [comment]
Hi,

Nice to know that price update is working... because according https://github.com/ig-python/ig-markets-api-python-library/issues/24 it was broken
I don't use this part API so I can't help but feel free to post here what you noticed (or [using email](https://github.com/femtotrader/)).

Kind regards

**Comment by RRMXkun** [comment]
- Items needs to be a list so items=['TRADE:'+self.accountId]
- Check #42 , there is another bug

Fixing these two things got it to work for me.

**Comment by firebird631** [comment]
I had a recent issue so I've moved ACCOUNT and TRADE subscribtions in first positions (before adding the MARKET) and now I can received them again.

**Comment by bug-or-feature** [comment]
Closing this. price and account updates are working ok in the ``/sample/stream_ig.py`` example
