### ISSUE TITLE
ValueError: columns cannot be a set

### ISSUE THREAD

**Issue by eg271** [ig-python/ig-markets-api-python-library#270]
Looks like Pandas new version (1.5.2) doesn't allow sets for columns so several locations in the code need to be adapted somehow:
```
            if len(data) == 0:
                data = pd.DataFrame(columns=self.colname_unique(cols))
                return data
```

**Comment by eg271** [comment]
Update: This is already handled in latest commits - just need to bump release version

**Comment by bug-or-feature** [comment]
0.0.19 released today includes the fix
