### ISSUE TITLE
ValueError: columns cannot be a set

### ISSUE THREAD

**Issue by oliverpolden** [ig-python/ig-markets-api-python-library#275]
I'm trying to update my code to use the latest version of trading_ig and I'm getting the error below. Can anyone help please?
Python 3.10
Pandas 1.5.2
  File "site-packages/trading_ig/rest.py", line 895, in fetch_open_positions
    data = pd.DataFrame(columns=self.colname_unique(cols))
  File "site-packages/pandas/core/frame.py", line 639, in __init__
    raise ValueError("columns cannot be a set")
ValueError: columns cannot be a set

**Comment by oliverpolden** [comment]
If I downgrade Pandas to 1.4.4 then this error goes away.

**Comment by bug-or-feature** [comment]
@oliverpolden this sounds like #270. That issue already has a fix committed, but it has not yet been included in a release. Until that happens, you could either reference this project's latest commit, or use a pandas version earlier than 1.5.2

**Comment by bug-or-feature** [comment]
0.0.19 released today includes the fix for #270
