### ISSUE TITLE
create_working_order raises validation.pattern.invalid.request.goodTillDate

### ISSUE THREAD

**Issue by femtotrader** [ig-python/ig-markets-api-python-library#32]
According [ElChups](https://twitter.com/elchups)

`create_working_order` raises 

    {"errorCode":"validation.pattern.invalid.request.goodTillDate"}

https://labs.ig.com/node/527

**Comment by femtotrader** [comment]
See https://github.com/ig-python/ig-markets-api-python-library/blob/372e7fcdf8fda8319f351feb08fd615615e02182/trading_ig/utils.py#L60
and https://github.com/ig-python/ig-markets-api-python-library/blob/372e7fcdf8fda8319f351feb08fd615615e02182/trading_ig/rest.py#L511

**Comment by fra-gh** [comment]
If it can help, the pattern that works for me is ` 3: "%Y/%m/%d %H:%M:%S"`. 
I see the code in the git is different from the version on PyPI, so maybe it's already fixed?

**Comment by bug-or-feature** [comment]
This issue is really old, is it still valid? I'll close shortly unless anyone speaks up...

**Comment by chix4030** [comment]
Hi,
I started to work with IG's API; 
When I want to sign into my account with API Companion or a programming platform, I receive the error below:

HTTP 400
....
"errorCode": "validation.pattern.invalid.authenticationRequest.identifier"

What's wrong with it?

**Comment by chix4030** [comment]
> This issue is really old, is it still valid? I'll close shortly unless anyone speaks up...

Do you think there should be a new issue for my problem?
