### ISSUE TITLE
Broken unit tests / CI need to be fixed

### ISSUE THREAD

**Issue by femtotrader** [ig-python/ig-markets-api-python-library#35]
ToDo

Related issue: https://github.com/ig-python/ig-markets-api-python-library/issues/2

**Comment by redbullpeter** [comment]
Shall we drop support for python 2.7? Continuing support means there's code refactoring to be done to make some of the current code backwards compatible which is why some of the CI tests are failing for 2.7

**Comment by femtotrader** [comment]
I only use Python 3.x.
See https://github.com/ig-python/ig-markets-api-python-library/issues/40

but aware that if https://github.com/ig-python/ig-markets-api-python-library/pull/39 doesn't pass. it's not a Python 2/3 issue

You can enable Travis with your fork repository and modify code in a branch... and when all is ok, send a PR.

**Comment by redbullpeter** [comment]
I've already enabled Travis CI and #39 passed for python 3.x but it failed for 2.7. This is because urllib has been split into urllib.request , urllib.parse and urllib.error packages in Python 3.x.

We're going to start seeing this kind of issue more frequently.

**Comment by bug-or-feature** [comment]
Support for 2.7 is dropped. All tests are passing in CI. Closing
