### ISSUE TITLE
Make a more object oriented approach for the stream part of this library

### ISSUE THREAD

**Issue by femtotrader** [ig-python/ig-markets-api-python-library#4]
This library need a better designed API (maybe an object oriented approach).
Signal/slot library or Publish-subscribe library could be use.

Signal/Slot: 
blinker https://pythonhosted.org/blinker/

Pub-sub:
PyPubSub http://pubsub.sourceforge.net/

**Comment by femtotrader** [comment]
The stream part need some improvement in API design

**Comment by bug-or-feature** [comment]
Is anyone still interested in this? I don't use the Stream part of the library, I cannot say if it would still be useful.

The issue has been untouched for 6 years; unless I hear otherwise I'll assume there's no need for it any more
