### ISSUE TITLE
Drop Python 2.7 support?

### ISSUE THREAD

**Issue by femtotrader** [ig-python/ig-markets-api-python-library#40]
Is there still people using Python 2.7 and this library?

Now, I only use Python 3 so we should consider dropping Python 2.7 support.

Any comment?

**Comment by redbullpeter** [comment]
No vote for me.

**Comment by dsdinter** [comment]
Hi,
2.7 is still required if you want, for instance, to integrate with other existing projects supporting that version, e.g.,  https://github.com/mhallsmoore/qstrader/pull/207


Kind regards.

**Comment by femtotrader** [comment]
My opinion is that QSTrader should drop Python 2.7 support.
There is many things to do in this project without having to deal with [technical debt](https://en.wikipedia.org/wiki/Technical_debt).
On my side I'm more and more involved in [Julia community](https://julialang.org/).
It's a great language with very good performances.

**Comment by dsdinter** [comment]
I agree, will suggest in Qstrader thread.

**Comment by OpenTrading** [comment]
I've been working with a large company that has very large Python projects that haven't even looked at Python3, so if you want other people to be able to use the library, Python2 is required. Also, it can depend of the Python that's with the Operating System that you are running on: there's lots of use of Ubuntu 14 in AWS projects, so Python2 is still esssential if the library is to be for use by other people. In corporate envrionments, I've seen people use Ubuntu 12 in production until the last day the LTS release was supported!

I think Wes is planning to drop support for Python2 next year in pandas, but even then, you can expect people to use the Python2 versions for a year or two after the new Python3-only versions come out. I have 2.7+3.4+3.5 and there's not a chance I'll be able to drop Python2 this year. C'est la vie.

**Comment by bug-or-feature** [comment]
Closing this. Support for 2.7 has been dropped
