### ISSUE TITLE
LSClient._forward_update_message issue with JSON-formatted responses

### ISSUE THREAD

**Issue by RRMXkun** [ig-python/ig-markets-api-python-library#42]
Hello

Issue is with this bit:

`tok = update_message.split(',')`
` table, item = int(tok[0]), tok[1]`

This works for prices where the format is:

> 1,1|00:06:28|1.08083|1.08089|0.00017|

in which case table is assigned 1, item is assigned '1|00:06:28|1.08083|1.08089|0.00017|' since the | character is unaffected by the split.

However it does not for TRADE, MARKET, etc where the output is instead JSON-like e.g.:

> 1,1|{"trailingStep":null,"trailingStopDistance":null,"stopLevel":null,"limitLevel":null,"guaranteedStop":false,"currency":"JPY","expiry":"-","dealIdOrigin":"DIAAAAA89UVURAX","direction":"SELL","epic":"","dealId":"","dealReference":"","dealStatus":"ACCEPTED","level":111.576,"status":"DELETED","size":0,"channel":"WEB","timestamp":"2017-03-21T23:44:27.177"}

As a consequence the split will turn the string into a list with multiple rows, and tok[1] will only hold (in this example) the following:
`1|{"trailingStep":null`

The rest of the information is lost.

Proposed fix: only split the first comma, leave rest of the string as is:
`tok = update_message.split(',', 1)`

This will not affect prices and resolve the issue. It is also compatible with Python 2 and 3.

Tested/reg-tested locally

Thanks

**Comment by femtotrader** [comment]
PR is welcome!

**Comment by RRMXkun** [comment]
Pull Request? I never used git before. Will give it a try this evening

**Comment by femtotrader** [comment]
https://help.github.com/articles/about-pull-requests/

Fork this repository.
Clone your repository

    git clone your_fork_repository

Create a branch to fix this issue

    git checkout -b name_of_your_new_branch

Modify code to fix issue / add feature(s)

Add your changes to repository and commit changes

    git add your_modified_files.py
    git commit

Push your code in your GitHub fork repository

    git push

Go to your fork repository on GitHub and create a PR

https://help.github.com/articles/creating-a-pull-request/

**Comment by RRMXkun** [comment]
Thanks - seems to have worked

**Comment by femtotrader** [comment]
I haven't test it but if you say me that it fix this issue I accept this PR.
Thanks for your contribution @RRMXkun
