### ISSUE TITLE
Switch account __set_headers

### ISSUE THREAD

**Issue by Dave-Vallance** [ig-python/ig-markets-api-python-library#50]
There is a call in the switch account method of the IGService object that calls `self.__set_headers()`

When I run the example script, I receive the error:

```
 File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trading_ig/rest.py", line 958, in switch_account
    self._set_headers(response.headers, False)
AttributeError: 'IGService' object has no attribute '_set_headers'
```

Am I missing something obvious or is this a bug? 

If I comment out the lines:

```
account_info = ig_service.switch_account(cfd, False) # not necessary
print(account_info)
```
Then I am able to run the example.

**Comment by femtotrader** [comment]
Hello @Dave-Vallance , (*)

How did you installed this library?
Where did you looked at doc?

Kind regards


(*) saying "Hello" is never useless (even on GitHub)

**Comment by Dave-Vallance** [comment]
Hello @femtotrader :)

Sorry, where are my manners? 

I installed the library via pip. The example I saw was on http://ig-markets-api-python-library.readthedocs.io

Thanks. Appreciate the insight and apologies in advance if I overlooked something.

**Comment by femtotrader** [comment]
You should install latest development version (because latest doc version is about this version)

https://github.com/ig-python/ig-markets-api-python-library#from-source

```
$ git clone https://github.com/ig-python/ig-markets-api-python-library.git
$ cd ig-markets-api-python-library
$ python setup.py install
```

or

```
$ pip install git+https://github.com/ig-python/ig-markets-api-python-library
```

I hope that helps.

If it solves your issue, please close.

**Comment by Dave-Vallance** [comment]
Thanks for the pointers....

Unfortunately running pip with the git link did not resolve the issue. Neither did cloning the repository and running setup.py. 

pip believes it has the latest version when (0.0.6). 

I managed to work around by copying the library from the cloned repository into my project folder. The account switch is now working. 

Not sure if you want to resolve it or think there may be something worth looking into on the setup side?

**Comment by Dave-Vallance** [comment]
Ok - Sorry, me being a dummy. I should have uninstalled trading_ig from pip first. Then installed the cloned version. 

Closing the issue

**Comment by femtotrader** [comment]
It's an install issue (because you didn't properly uninstall your previously installed version)

    $ pip uninstall trading_ig 

run Python interpreter

ensure that this lib is not in your Python installation

    import trading_ig

should raise an ImportError exception

and after install latest version

**Comment by femtotrader** [comment]
ok. I've just notice your previous post
