### ISSUE TITLE
create_order_position does not include timeInForce parameter

### ISSUE THREAD

**Issue by jimbob041** [ig-python/ig-markets-api-python-library#62]
I'm trying to send a market order by using this code:

```python
response = ig_service.create_open_position(currency_code='GBP', direction='BUY', 
                                           epic='IX.D.DOW.MONTH1.IP', expiry='-', 
                                           force_open='false', guaranteed_stop='false', 
                                           level='', limit_distance='', limit_level='', 
                                           order_type='MARKET', quote_id='', size=0.5, 
                                           stop_distance='', stop_level='')

print(response)
```
I get this response:
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
<p>Additionally, a 406 Not Acceptable
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```
I think it may be because there is no timeInForce parameter as on IG's API Companion it's one of the parameters that needs to be filled in?

**Comment by hklang10** [comment]
wierd - I'm messing around with this in the API companion.  

If I place an order using this content:
```
{
    "epic": "IX.D.DOW.MONTH1.IP",
    "expiry": "-",
    "direction": "BUY",
    "size": "0.5",
    "orderType": "MARKET",
    "timeInForce": null,
    "level": null,
    "guaranteedStop": "false",
    "stopLevel": null,
    "stopDistance": null,
    "trailingStop": null,
    "trailingStopIncrement": null,
    "forceOpen": "false",
    "limitLevel": null,
    "limitDistance": null,
    "quoteId": null,
    "currencyCode": "GBP"
}

```
I can then use this content for the next order .....
`   {
    "epic": "IX.D.DOW.MONTH1.IP",
    "expiry": "-",
    "direction": "BUY",
    "size": 0.5,
    "orderType": "MARKET",
    "guaranteedStop": "false",
    "forceOpen": "false",
    "currencyCode": "GBP"
}`

but this code does never works:

{
    'epic': 'IX.D.DOW.MONTH1.IP',
    'expiry': '-',
    'direction': 'BUY',
    'size': 0.5,
    'orderType': 'MARKET',
    'guaranteedStop': 'false',
    'forceOpen': 'false',
    'currencyCode': 'GBP'
}

**Comment by hklang10** [comment]
Unless this is the OP escalating the issue, this appears to be a backend problem?  See https://labs.ig.com/node/708

**Comment by bug-or-feature** [comment]
Closing this, old issue
