### ISSUE TITLE
Question: Lightstreamer.py commits

### ISSUE THREAD

**Issue by Dave-Vallance** [ig-python/ig-markets-api-python-library#70]
Hello,
  Just wondering, do you accept commits to the lightstreamer.py file? Since it looks like it was created by 3rd party (Lightstreamer Srl.), I guess that you may want to keep in sync with them?

I noticed that the error reporting for lighstreamer is not too helpful. When an error occurs, the `_control()` method just returns the first line of the error which just says "ERROR". 

I have an edit to return the full error when it happens but also just return 'OK' when there is not. I can submit a pull request if you are interested. 

Cheers

**Comment by femtotrader** [comment]
Hi @Dave-Vallance 

You might have a look at
https://github.com/Lightstreamer/Lightstreamer-example-StockList-client-python/issues/1
I still don't understand relationship and differences between https://github.com/dw/py-lightstreamer and https://github.com/Lightstreamer/Lightstreamer-example-StockList-client-python
Pinging @dw and @gfinocchiaro 
Having a real Python package would help to tackle the problem you are raising

Kind regards

**Comment by dw** [comment]
Hi, thanks for bringing this to my attention. It seems the lightstreamer.py in this repository, carrying Lightstreamer Srl's copyright, has a great deal in common with my py-lightstreamer code, despite not carrying the original copyright, in violation of the license. Many of the constants, class names, and e.g. the implementation of _decode_field look almost identical.

Will dig into this at some later time when I'm not so busy

**Comment by gfinocchiaro** [comment]
Hi,

Initially, I have been certainly inspired by the excellent @dw's work but actually, the two implementations are very different, as you can see by comparing the source code.
Yes,  `_decode_field`  is very similar to `_decode`, but the logic here is so trivial and also driven by the protocol specifications. And yes, few constant names and only one class name (`LSClient`) are almost identical.
By the way, I'm willing to change such names and everything he might believe could violate his original source code. Ask @dw to contact me privately to shed some light on this issue.

We are planning to make the demo as a Python package in the short term.

**Comment by dw** [comment]
If I can accidentally spot code derived from something I haven't touched for over 5 years, then it should almost certainly still bear the original copyright. The attribution wasn't even directly to me, it's to "the py-lightstreamer authors", which should be trivial to restore. I'm not going to through the files statement-for-statement (an issue like this isn't worth that), but just to say the feeling of familiarity had already started with the blocks of imports at the top of the file!

**Comment by gfinocchiaro** [comment]
It looks like that the two blocks of imports are quite different. Anyway, as already anticipated, we are going to publish a brand new Python package, with new source code from scratch. Obviously, even the mentioned demo project will be updated as well.

**Comment by femtotrader** [comment]
Nice to know that a real package on which we could rely will be released. I think that ig-python developers and users will be very pleased to be informed when it will be available.
