### ISSUE TITLE
Limitations on historical 1 Minute data using REST API?

### ISSUE THREAD

**Issue by Mokers123** [ig-python/ig-markets-api-python-library#72]
Hi,

Thanks for the contribution.

When I attempt to print to console historical data using the fetch_historical_prices_by_epic_and_date_range function, the resulting data is compressed. Eg. to print one day of 1 Minute data, it is returned in book-ended 30-data-point chunks (as below). There is no such concern for printing a large quantity of Daily data.

Example:

ask prices:
                        Open     High      Low    Close
DateTime                                               
2017:11:10-00:00:00  1.16471  1.16471  1.16448  1.16455
2017:11:10-00:01:00  1.16454  1.16488  1.16448  1.16485
2017:11:10-00:02:00  1.16486  1.16512  1.16479  1.16479
2017:11:10-00:03:00  1.16480  1.16489  1.16474  1.16485
2017:11:10-00:04:00  1.16483  1.16494  1.16480  1.16489
2017:11:10-00:05:00  1.16488  1.16497  1.16486  1.16489
2017:11:10-00:06:00  1.16490  1.16512  1.16489  1.16500
2017:11:10-00:07:00  1.16499  1.16503  1.16494  1.16499
2017:11:10-00:08:00  1.16500  1.16515  1.16493  1.16509
2017:11:10-00:09:00  1.16508  1.16517  1.16497  1.16516
2017:11:10-00:10:00  1.16515  1.16527  1.16509  1.16523
2017:11:10-00:11:00  1.16522  1.16532  1.16516  1.16517
2017:11:10-00:12:00  1.16516  1.16522  1.16503  1.16503
2017:11:10-00:13:00  1.16504  1.16542  1.16497  1.16532
2017:11:10-00:14:00  1.16531  1.16537  1.16518  1.16523
2017:11:10-00:15:00  1.16524  1.16526  1.16514  1.16518
2017:11:10-00:16:00  1.16519  1.16521  1.16508  1.16516
2017:11:10-00:17:00  1.16515  1.16519  1.16504  1.16509
2017:11:10-00:18:00  1.16508  1.16518  1.16508  1.16510
2017:11:10-00:19:00  1.16511  1.16516  1.16498  1.16498
2017:11:10-00:20:00  1.16497  1.16501  1.16487  1.16488
2017:11:10-00:21:00  1.16489  1.16493  1.16481  1.16488
2017:11:10-00:22:00  1.16487  1.16493  1.16479  1.16488
2017:11:10-00:23:00  1.16487  1.16506  1.16487  1.16504
2017:11:10-00:24:00  1.16499  1.16503  1.16493  1.16494
2017:11:10-00:25:00  1.16495  1.16509  1.16494  1.16504
2017:11:10-00:26:00  1.16505  1.16512  1.16498  1.16504
2017:11:10-00:27:00  1.16505  1.16507  1.16491  1.16496
2017:11:10-00:28:00  1.16495  1.16503  1.16491  1.16499
2017:11:10-00:29:00  1.16497  1.16503  1.16495  1.16498
...                      ...      ...      ...      ...
2017:11:10-21:29:00  1.16653  1.16657  1.16648  1.16653
2017:11:10-21:30:00  1.16654  1.16654  1.16652  1.16653
2017:11:10-21:31:00  1.16657  1.16657  1.16648  1.16649
2017:11:10-21:32:00  1.16648  1.16649  1.16648  1.16649
2017:11:10-21:33:00  1.16648  1.16659  1.16648  1.16654
2017:11:10-21:34:00  1.16653  1.16659  1.16652  1.16653
2017:11:10-21:35:00  1.16658  1.16660  1.16653  1.16655
2017:11:10-21:36:00  1.16654  1.16658  1.16652  1.16657
2017:11:10-21:37:00  1.16652  1.16657  1.16648  1.16648
2017:11:10-21:38:00  1.16649  1.16649  1.16648  1.16648
2017:11:10-21:39:00  1.16647  1.16657  1.16647  1.16657
2017:11:10-21:40:00  1.16652  1.16657  1.16651  1.16652
2017:11:10-21:41:00  1.16653  1.16654  1.16648  1.16648
2017:11:10-21:42:00  1.16652  1.16654  1.16647  1.16649
2017:11:10-21:43:00  1.16648  1.16650  1.16648  1.16649
2017:11:10-21:44:00  1.16648  1.16649  1.16647  1.16648
2017:11:10-21:45:00  1.16649  1.16658  1.16648  1.16653
2017:11:10-21:46:00  1.16648  1.16657  1.16646  1.16649
2017:11:10-21:47:00  1.16648  1.16657  1.16647  1.16655
2017:11:10-21:48:00  1.16656  1.16658  1.16647  1.16657
2017:11:10-21:49:00  1.16658  1.16695  1.16654  1.16694
2017:11:10-21:50:00  1.16692  1.16694  1.16661  1.16670
2017:11:10-21:51:00  1.16671  1.16677  1.16664  1.16670
2017:11:10-21:52:00  1.16671  1.16678  1.16668  1.16672
2017:11:10-21:53:00  1.16678  1.16678  1.16662  1.16663
2017:11:10-21:54:00  1.16662  1.16663  1.16654  1.16659
2017:11:10-21:55:00  1.16660  1.16663  1.16649  1.16653
2017:11:10-21:56:00  1.16652  1.16655  1.16648  1.16650
2017:11:10-21:57:00  1.16651  1.16661  1.16648  1.16652
2017:11:10-21:58:00  1.16654  1.16673  1.16651  1.16655

[1315 rows x 4 columns]

**Comment by RRMXkun** [comment]
They *appear* truncated but this is just how Panda DataFrames print; they do this so not to flood the standard output. The data is still stored in memory.

Try:

```
print('Date', 'Open', 'High', 'Low', 'Close' )
for index, row in res['prices'].iterrows() :
    print(index, row.ask.Open, row.ask.High, row.ask.Low, row.ask.Close)
```

Replace row.ask with row.bid, etc as needed

**Comment by bug-or-feature** [comment]
This is not an issue, just a misunderstanding of how pandas works. Closing
