### ISSUE TITLE
I'm getting lightstreamer deamon not available, what should I do?

### ISSUE THREAD

**Issue by jappeace** [ig-python/ig-markets-api-python-library#73]
Is there some package I need to install?
This is the warning:

    WARNING:trading_ig.lightstreamer:systemd.daemon not available, no watchdog notifications will be sent.

**Comment by eg271** [comment]
same here

**Comment by jappeace** [comment]
I think you can just ignore this error, I remember at some point getting prices.

**Comment by bug-or-feature** [comment]
Closing, resolved

**Comment by whittlem** [comment]
I'm getting this same issue on OSX. Why was this closed?

**Comment by aristizabal95** [comment]
Also getting this in OSX

**Comment by bug-or-feature** [comment]
Re-opening. The PR in #92 was never merged in

**Comment by CZJ1018** [comment]
I'm osx too, Re-opening also can't wok, why?

**Comment by CZJ1018** [comment]
I'm OSX too,re-opening also cannot be executed,why?

**Comment by bug-or-feature** [comment]
Change from PR #92 added, closing
