### ISSUE TITLE
ig_service.fetch_open_positions()

### ISSUE THREAD

**Issue by Sasanita** [ig-python/ig-markets-api-python-library#86]
ig_service.fetch_open_positions() returns one position less than it should. On the ig web platform I have 3 opened position but ig_service.fetch_open_positions() returns only 2 first positions.

**Comment by Sasanita** [comment]
Sorry. It seems that the api needs time to update the data.

**Comment by femtotrader** [comment]
Feel free to contribute @Sasanita

**Comment by Sasanita** [comment]
ps. The update of positions depends of expire_after time of equests_cache.CachedSession ;)

**Comment by femtotrader** [comment]
You can pass `session = requests.Session()` to avoid caching but I think it's default parameter settings according https://github.com/ig-python/ig-markets-api-python-library/blob/3cd3b49bf4c13e88f034e23684759da908d7652d/trading_ig/rest.py#L193-L194
