### ISSUE TITLE
create_working_order

### ISSUE THREAD

**Issue by Fux002** [ig-python/ig-markets-api-python-library#88]
Hey all i get this error when: create_working_order

response = session.post(url,
AttributeError: 'dict' object has no attribute 'post'

Has anyone seen this?

+++++++++++++++++++++

create_w_order(
		currency_code ='USD', 
		direction = 'BUY', 
		epic = 'IX.D.SPTRD.IFM.IP', 
		expiry = "-",
        good_till_date = datetime.datetime.now(pytz.timezone('UTC')), 
        guaranteed_stop = "true", 
        level = 'null',
        limit_distance = '0.1', 
        limit_level = '2900', 
        size = '1', 
        stop_distance  = '2900',
        stop_level = '2900', 
        time_in_force = 'null', 
        order_type = "LIMIT")

**Comment by femtotrader** [comment]
Hello @Fux002 ,

could you provide a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example).
Please also use [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) for code.

Kind regards

**Comment by Fux002** [comment]
Hi thank you for the reply:

please see below attached you just have to add your login details.

Thx a lot!

**Comment by Fux002** [comment]
o sorry cant attache .py files here the code i used in my example:

+++++++++++++++++++


import time
import sys
import pytz
import datetime
import traceback
import logging
import settings
import db_connect
import stream_writer

import pandas as pd
import numpy as np

from trading_ig import (IGService, IGStreamService)
from trading_ig.lightstreamer import Subscription


# Identification settings
USERNAME        = settings.ig_username
PASSWORD        = settings.ig_password
API_KEY         = settings.ig_api_key
ACCOUNT_TYPE    = settings.ig_account_type
ACCOUNT_NUMBER  = settings.ig_account_number


class IGtrader(object):
	_ig_service = None
	_ig_session = None
	Odb_object = None
	Odb_connection = None

	def __init__(self):
		print ('IG Trader Object Initialized')
		self._ig_service = IGService(USERNAME, PASSWORD, API_KEY, ACCOUNT_TYPE)
		self._ig_session = self._ig_service.create_session()


	def create_w_order(self, currency_code, direction, epic, expiry,
                             good_till_date, guaranteed_stop, level,
                             limit_distance, limit_level, size, stop_distance,
                             stop_level, time_in_force, order_type):
		""" Create working order. """
		self._ig_service.create_working_order(currency_code, direction, epic, expiry,
                             good_till_date, guaranteed_stop, level,
                             limit_distance, limit_level, size, stop_distance,
                             stop_level, time_in_force, order_type,
                             self._ig_session)


if __name__ == '__main__':
	igObj = IGtrader()

	igObj.create_w_order(
		'USD',
		'BUY',
		'IX.D.SPTRD.IFM.IP',
		'-',
		datetime.datetime.now(pytz.timezone('UTC')),
		'true',
		'1',
		'1',
		'50',
		'4',
		'5',
		'6',
		'null',
		'LIMIT')

**Comment by Fux002** [comment]
Any comment anyone please?

**Comment by CZJ1018** [comment]
Hey bro, I have the same question now.
How is your solution to this problem? 
If you see me plz reply to me Thank🙏.

**Comment by Fux002** [comment]
Hey remind me the problem please was a long time ago and I resolved it in the mean time

**Comment by Fux002** [comment]
Here are the default parameters

I think you time stamp is the wrong format. But could be more issues. It’s rather sensitive.


good_till_date = None
		limit_distance = None
		level = round(self._px_ask * float(new_buy_stop_distance),self._decimalPlacesFactor)
		limit_level = None
		stop_distance = the_next_gstop_distance #gstop 1% below buy price, thi is always None as not sed
		stop_level = None
		limit_distance = None
		time_in_force = "GOOD_TILL_CANCELLED"
		order_type = "STOP"
		guaranteed_stop = "false"
		deal_id = the_deal_id
