### ISSUE TITLE
Utils.py

### ISSUE THREAD

**Issue by Fux002** [ig-python/ig-markets-api-python-library#90]
Can we please change the data format in the utils file

to create working orders you need format 3

        d_formats = {
            1: "%Y:%m:%d-%H:%M:%S",
            2: "%Y-%m-%d %H:%M:%S",
            3: "%Y/%m/%d %H:%M:%S"
        }

thx a lot!

**Comment by femtotrader** [comment]
https://github.com/ig-python/ig-markets-api-python-library/blob/3cd3b49bf4c13e88f034e23684759da908d7652d/trading_ig/utils.py#L60-L79

Why not fixing it yourself and submit a Pull Request?

https://github.com/ig-python/ig-markets-api-python-library/blob/3cd3b49bf4c13e88f034e23684759da908d7652d/trading_ig/rest.py#L578-L588


Format used for working order seems to be "%Y/%m/%d %H:%M:%S"

**Comment by Fux002** [comment]
i dont like working with github;.

**Comment by bug-or-feature** [comment]
Closing this. version 3 date format was added some time ago
