### ISSUE TITLE
DUPLICATE_ORDER_ERROR

### ISSUE THREAD

**Issue by firebird631** [ig-python/ig-markets-api-python-library#91]
When I create_open_position sometime I've a DUPLICATE_ORDER_ERROR but I don't know what I did wrong because it works the rest of time. It seems random. I'll try to contact IG but I would to know if you have an idea before, and if its about an argument or an issue of the library.

**Comment by femtotrader** [comment]
sorry no idea. I don't use ig-markets-api-python-library currently

**Comment by firebird631** [comment]
ok its when I pass two order on the same instrument and with the same quantity quickly, So if I wait 1 sec between the orders it works. I don't know if there is a proper way to prevent that.

**Comment by femtotrader** [comment]
Sorry but I'm not sure help...maybe ask IG support

**Comment by RRMXkun** [comment]
I had it before but it can occur in multiple scenarios. Do you have a code snippet to share?

**Comment by RRMXkun** [comment]
> 
> 
> ok its when I pass two order on the same instrument and with the same quantity quickly, So if I wait 1 sec between the orders it works. I don't know if there is a proper way to prevent that.

Remember you have a lag between the time your order is sent, processed, then executed. It will stand in the order queue for a little while (a second or two). There probably isn't much you can do besides waiting with sleep() unfortunately.

**Comment by firebird631** [comment]
An execution list with a timestamp of the last order submission would be the proper way. IG had confirm me they have a such protection to avoid duplication of orders when instrument direction and quantity are the same.

**Comment by bug-or-feature** [comment]
Closing old issue
