### ISSUE TITLE
Session close

### ISSUE THREAD

**Issue by Fux002** [ig-python/ig-markets-api-python-library#93]
Hi all is there a way to test id the session is still active? 

I like to prevent the below.

Thx!

File "/home/fonsv/.virtualenvs/adas_envpy37/lib/python3.5/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

**Comment by mickael-h** [comment]
Same problem here.

**Comment by RRMXkun** [comment]
I have encountered the same issue, though the error message was different. Seems to happen if the connection to IG has been idle for some time, when trying to execute a request the above exception is returned. Though strangely, if the request is sent again right after with the same connection, it seems to go through fine.

**Comment by bug-or-feature** [comment]
Closing this issue. There's some new FAQs in the [docs](https://trading-ig.readthedocs.io/en/latest/faq.html) relating to login/sessions
