### ISSUE TITLE
Exception: Environment variable 'IG_SERVICE_USERNAME' doesn't exist

### ISSUE THREAD

**Issue by gg4u** [ig-python/ig-markets-api-python-library#97]
Just installed - playing around:

I created a `trading_ig_config.py`  (` cp trading_ig_config.default.py trading_ig_config.py` , with my credentials).

run `python sample/rest_ig.py`

```
can't import config from config file
Traceback (most recent call last):
  File "/Users/gg4u/Sites/tradingDemo/venv/lib/python3.7/site-packages/trading_ig/config.py", line 26, in __getattr__
    return(os.environ[env_var])
  File "/Users/gg4u/Sites/miniconda3/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'IG_SERVICE_USERNAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sample/rest_ig.py", line 89, in <module>
    main()
  File "sample/rest_ig.py", line 35, in main
    config.username, config.password, config.api_key, config.acc_type
  File "/Users/gg4u/Sites/tradingDemo/venv/lib/python3.7/site-packages/trading_ig/config.py", line 28, in __getattr__
    raise Exception("Environment variable '%s' doesn't exist" % env_var)
Exception: Environment variable 'IG_SERVICE_USERNAME' doesn't exist
```
Can you advice ?

**Comment by femtotrader** [comment]
You can pass your config (username, password) using a config file or using environment variable

it seems here that you are trying to pass (username and probably password) using environment variable but it's not set.

https://www.google.com/search?q=environment+variable+windows
https://www.google.com/search?q=environment+variable+linux

**Comment by geriski** [comment]
> Just installed - playing around:
> 
> I created a `trading_ig_config.py` (` cp trading_ig_config.default.py trading_ig_config.py` , with my credentials).
> 
> run `python sample/rest_ig.py`
> 
> ```
> can't import config from config file
> Traceback (most recent call last):
>   File "/Users/gg4u/Sites/tradingDemo/venv/lib/python3.7/site-packages/trading_ig/config.py", line 26, in __getattr__
>     return(os.environ[env_var])
>   File "/Users/gg4u/Sites/miniconda3/lib/python3.7/os.py", line 678, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'IG_SERVICE_USERNAME'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "sample/rest_ig.py", line 89, in <module>
>     main()
>   File "sample/rest_ig.py", line 35, in main
>     config.username, config.password, config.api_key, config.acc_type
>   File "/Users/gg4u/Sites/tradingDemo/venv/lib/python3.7/site-packages/trading_ig/config.py", line 28, in __getattr__
>     raise Exception("Environment variable '%s' doesn't exist" % env_var)
> Exception: Environment variable 'IG_SERVICE_USERNAME' doesn't exist
> ```
> 
> Can you advice ?

Higg4u,

I had the same problem. You need to create the trading_ig_config.py file next to your code, not in the ig-python package.

Regards,Gergely

**Comment by bug-or-feature** [comment]
Resolved, closing

**Comment by phj6688** [comment]
> 

I still get the error
